#!/usr/bin/env sh
#dotnet - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists dotnet; then
    pmmux brew!'brew cask install dotnet-sdk' pacman+dotnet-sdk
fi

exec dotnet "$@"
