#!/usr/bin/env sh
#fzy - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists fzy; then
    pmmux apk+'gcc musl-dev'
    pmmux apt+fzy pacman+fzy brew+fzy
        git!'https://github.com/jhawthorn/fzy.git master \
            make PREFIX="$PREFIX" install >&2'
fi

exec fzy "$@"
