#!/usr/bin/env sh
#git-credential-pass - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" \
        exists git-credential-pass; then
    pmmux git!'https://github.com/milhnl/pass.git master \
        make PREFIX="$PREFIX" install >&2'
fi

exec git-credential-pass "$@"
