#!/usr/bin/env sh
#go - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists go; then
    pmmux apk+go apt+golang-go brew+go pacman+go
fi

exec go "$@"
