#!/usr/bin/env sh
#jq - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists jq; then
    pmmux apk+jq apt+jq brew+jq dnf+jq pacman+jq
fi

exec jq "$@"
