#!/usr/bin/env sh
#man - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists man; then
    pmmux apk+'man man-pages' pacman+'man-db man-pages'
fi

exec man "$@"
