#!/usr/bin/env sh
#mpmc - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists mpmc; then
    pmmux apk+python3-dev
    pmmux pip+'matrix-nio aiofiles'
    pmmux git!'https://github.com/milhnl/mpmc.git master \
        make PREFIX="$PREFIX" install >&2'
fi

exec mpmc "$@"
