#!/usr/bin/env sh
#rg - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists rg; then
    pmmux apk+ripgrep apt+ripgrep brew+ripgrep pacman+ripgrep
fi

exec rg "$@"
