#!/usr/bin/env sh
#subliminal - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists subliminal; then
    pmmux pip+subliminal
fi

exec subliminal "$@"
