#!/usr/bin/env sh
#swayidle - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists swayidle; then
    pmmux apk+swayidle apt+swayidle dnf+swayidle pacman+swayidle
fi

exec swayidle "$@"
