#!/usr/bin/env sh
#swaylock - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists swaylock; then
    pmmux apk+swaylock apt+swaylock pacman+swaylock
fi

exec swaylock "$@"
