#!/usr/bin/env sh
#yay - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists yay; then
    sudo pacman --needed --noconfirm -qS base-devel
    pmmux git!'https://aur.archlinux.org/yay.git master makepkg -si'
fi

exec yay "$@"
