#!/usr/bin/env sh
#youtube-dl - lazyload
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! PATH="`echo "$PATH"|sed 's/:[^:]*lazyload//'`" exists youtube-dl; then
    pmmux apk+youtube-dl brew+youtube-dl dnf+youtube-dl pacman+youtube-dl
fi

exec youtube-dl "$@"
