#!/usr/bin/env sh
<"$XDG_CONFIG_HOME/alacritty/light.toml" awk '
        /^\[/ { section = substr($0, 2, length($0) - 2) }
        /=/ { print section "." $0 }
    ' | tr '\n' '\0' | xargs -0 -L 1 alacritty msg config -w -1
