#!/usr/bin/env sh
set -eu

sudo pacman --needed --noconfirm -qS radicale
sudo cp calendarserver/config /etc/radicale/config
sudo mkdir -p /srv/radicale
sudo chown -R radicale:radicale /srv/radicale

[ -e /srv/radicale/.rights ] || printf '%s\n' \
        '[principal]' \
        'user: .+' \
        'collection: {user}' \
        'permissions: RW' \
        '' \
        '[calendars]' \
        'user: .+' \
        'collection: {user}/[^/]+' \
        'permissions: rw' \
    | sudo tee /srv/radicale/.rights >/dev/null

sudo chown root:root /etc/radicale/config

sudo mkdir -p /etc/systemd/system/radicale.service.d
printf '[Service]\nReadWritePaths=/srv/radicale\n' \
    | sudo tee /etc/systemd/system/radicale.service.d/override.conf
sudo systemctl daemon-reload

sudo systemctl enable radicale
sudo systemctl restart radicale
