#!/usr/bin/env sh
set -eu

sudo pacman --needed --noconfirm -qS radicale

sudo systemd-tmpfiles --create - <<EOF
C+ /etc/radicale/config    -    -        -        - $PWD/calendarserver/config
d  /srv/radicale           0700 radicale radicale
f  /srv/radicale/.htpasswd 0700 radicale radicale
C  /srv/radicale/rights    -    -        -        - $PWD/calendarserver/rights
C+ /etc/nginx/templates/radicale - -     -        - $PWD/calendarserver/nginx-location.conf
EOF

sudo mkdir -p /etc/systemd/system/radicale.service.d
printf '[Service]\nReadWritePaths=/srv/radicale\n' \
	| sudo tee /etc/systemd/system/radicale.service.d/override.conf
sudo systemctl daemon-reload

sudo systemctl enable radicale
sudo systemctl restart radicale
