#!/usr/bin/env sh
#website - set up website with nginx or apache
set -eu

echo() { printf "%s" "$*"; }
exists() { command -v "$1" >/dev/null 2>&1; }
in_dir() ( cd "$1"; shift; "$@"; )

lineinfile() { #1: path, 2: regexp, 3: line
    [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
    if grep -qF "^$3$" "$1" 2>/dev/null; then
        return
    elif grep -q "$2" "$1" 2>/dev/null; then
        set -- "$1" "$2" "$3" "$(mktemp)"
        sed "s/.*$(echo "$2"|sed 's_/_\\/_').*/$(echo "$3"|sed 's_/_\\/_')/" \
            <"$1" >"$4"
        sudo mv "$4" "$1"
    else
        sudo sh -c 'echo "$3" >>"$1"' - "$@"
    fi
}

TEMPLATE="${TEMPLATE:-static}"
FQDN="${FQDN:-$([ -n "$BASE_URL" ] \
    && echo "$BASE_URL" | sed -E 's_(https?://)?([^/:]*).*_\2_' \
    || echo "$HOSTNAME")}"
URL_PREFIX="${URL_PREFIX:-$([ -n "$BASE_URL" ] \
    && echo "$BASE_URL" | sed -E 's_(https?://)?([^/]*)/?__')}"
PORT="${PORT:-$( \
    echo "$BASE_URL" | sed -E 's_(https?://)?[^/:]*(:([0-8]*))?.*_\3_')}" \
FILENAME="$FQDN${PORT:+:$PORT}"
LOCATION="${LOCATION:-/srv/http/$FILENAME}"
PORT="${PORT:-80}"

if [ "$TEMPLATE" = reverseproxy ]; then
    : "$PROXY_PASS" #error if unset
elif [ "$TEMPLATE" = php ]; then
    sudo pacman --needed --noconfirm -qS php-fpm
    sudo systemctl enable --now php-fpm
    FASTCGI_PASS=unix:/run/php-fpm/php-fpm.sock
elif [ "$TEMPLATE" = php7 ]; then
    sudo pacman --needed --noconfirm -qS php7-fpm
    sudo systemctl enable --now php-fpm7
    FASTCGI_PASS=unix:/run/php-fpm7/php-fpm.sock
    TEMPLATE=php
elif [ "$TEMPLATE" = static ] || [ "$TEMPLATE" = static-protected ]; then
    sudo mkdir -p "$LOCATION"
fi

case "${HTTPD-nginx}" in
apache)
    if exists pacman; then
        DAEMON=httpd
    elif exists apt-get; then
        DAEMON=apache2
    fi
    [ "$TEMPLATE" = php ] && TEMPLATE=static ||:
    sudo mkdir -p "/etc/$DAEMON/templates/"
    sudo cp "website/apache-templates"/* "/etc/$DAEMON/templates/"
    in_dir "/etc/$DAEMON/templates" cat "$TEMPLATE" \
        | sed \
            -e "s/\\\$FQDN/$FQDN/" \
            -e "s/\\\$PORT/$PORT/" \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/$DAEMON/sites/$FILENAME.conf" >/dev/null
    cat "/etc/$DAEMON/sites/"*.conf \
        | sed -n 's/<VirtualHost [^: \/]*:\([0-9]*\)>.*/Listen \1/p' \
        | sudo tee "/etc/$DAEMON/ports.conf" >/dev/null
    sudo systemctl restart "$DAEMON"
    ;;
nginx)
    sudo mkdir -p "/etc/nginx/templates/"
    sudo cp "website/nginx-templates"/* "/etc/nginx/templates/"
    in_dir "/etc/nginx/templates" cat "$TEMPLATE" \
        | sed \
            -e "s/\\\$FQDN/$FQDN/" \
            -e "s/\\\$PORT/$PORT/" \
            -e "s \\\$PROXY_PASS ${PROXY_PASS-gimme_an_error} " \
            -e "s \\\$FASTCGI_PASS ${FASTCGI_PASS-gimme_an_error} " \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/nginx/sites/$FILENAME.conf" >/dev/null
    sudo systemctl reload nginx || sudo systemctl restart nginx || true
    ;;
esac

