#!/usr/bin/env sh
#website - set up website with nginx or apache
set -eu

die() { printf '%s\n' "$*" >&2; exit 1; }
echo() { printf "%s" "$*"; }
exists() { command -v "$1" >/dev/null 2>&1; }
in_dir() ( cd "$1"; shift; "$@"; )
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; sudo mv "$2" "$1"; }

lineinfile() { #1: path, 2: regexp, 3: line
    [ $# -eq 2 ] && set -- "$1" "^$2\$" "${3:-$2}" || true
    if grep -qF "^$3$" "$1" 2>/dev/null; then
        return
    elif grep -q "$2" "$1" 2>/dev/null; then
        set -- "$1" "$2" "$3" "$(mktemp)"
        sed "s/.*$(echo "$2"|sed 's_/_\\/_').*/$(echo "$3"|sed 's_/_\\/_')/" \
            <"$1" >"$4"
        sudo mv "$4" "$1"
    else
        sudo sh -c 'echo "$3" >>"$1"' - "$@"
    fi
}

TEMPLATE="${TEMPLATE:-static}"
FQDN="${FQDN:-$([ -z "${BASE_URL-}" ] \
    || echo "$BASE_URL" | sed -E 's_(https?://)?([^/:]*).*_\2_')}"
URL_PREFIX="${URL_PREFIX:-$([ -z "${BASE_URL-}" ] \
    || echo "$BASE_URL" | sed -E 's_(https?://)?([^/]*)/?__')}"
PORT="${PORT:-$( \
    echo "${BASE_URL-}" | sed -E 's_(https?://)?[^/:]*(:([0-8]*))?.*_\3_')}" \
FILENAME="${FQDN:-localhost}${PORT:+:$PORT}"
LOCATION="${LOCATION:-/srv/http/$FILENAME}"
LEVEL="${LEVEL:-$([ -n "$URL_PREFIX" ] && echo location || echo server)}"

if [ "$TEMPLATE" = reverseproxy ]; then
    : "$PROXY_PASS" #error if unset
elif [ "$TEMPLATE" = php ]; then
    sudo pacman --needed --noconfirm -qS php-fpm
    sudo systemctl enable --now php-fpm
    FASTCGI_PASS=unix:/run/php-fpm/php-fpm.sock
elif [ "$TEMPLATE" = php7 ]; then
    sudo pacman --needed --noconfirm -qS php7-fpm
    sudo systemctl enable --now php-fpm7
    FASTCGI_PASS=unix:/run/php-fpm7/php-fpm.sock
    TEMPLATE=php
elif [ "$TEMPLATE" = static ] || [ "$TEMPLATE" = static-protected ]; then
    sudo mkdir -p "$LOCATION"
fi

case "${HTTPD-nginx}" in
apache)
    if exists pacman; then
        DAEMON=httpd
    elif exists apt-get; then
        DAEMON=apache2
    fi
    [ "$TEMPLATE" = php ] && TEMPLATE=static ||:
    sudo mkdir -p "/etc/$DAEMON/templates/"
    sudo cp "website/apache-templates"/* "/etc/$DAEMON/templates/"
    in_dir "/etc/$DAEMON/templates" cat "$TEMPLATE" \
        | sed \
            -e "s/\\\$FQDN/$FQDN/" \
            -e "s/\\\$PORT/${PORT:-80}/" \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/$DAEMON/sites/$FILENAME.conf" >/dev/null
    cat "/etc/$DAEMON/sites/"*.conf \
        | sed -n 's/<VirtualHost [^: \/]*:\([0-9]*\)>.*/Listen \1/p' \
        | sudo tee "/etc/$DAEMON/ports.conf" >/dev/null
    sudo systemctl restart "$DAEMON"
    ;;
nginx)
    [ "$LEVEL" = server ] || sudo mkdir -p "/etc/nginx/sites/$FILENAME.d"
    sudo mkdir -p "/etc/nginx/templates/"
    sudo cp "website/nginx-templates"/* "/etc/nginx/templates/"
    in_dir "/etc/nginx/templates" cat "$TEMPLATE" \
        | \
            if [ "$LEVEL" = server ]; then
                printf "%s\n" \
                    "server {" \
                    "    server_name \"$FQDN\";" \
                    "    listen ${PORT:-80};" \
                    "    include sites/$FILENAME.d/*.conf;"
                cat
                printf "}\n"
            else
                cat
            fi \
        | sed \
            -e "s/\\\$FILENAME/$FILENAME/" \
            -e "s \\\$URL_PREFIX ${URL_PREFIX} " \
            -e "s/\\\$FQDN/$FQDN/" \
            -e "s/\\\$PORT/${PORT:-80}/" \
            -e "s \\\$PROXY_PASS ${PROXY_PASS-gimme_an_error} " \
            -e "s \\\$FASTCGI_PASS ${FASTCGI_PASS-gimme_an_error} " \
            -e "s \\\$LOCATION $LOCATION " \
        | sudo tee "/etc/nginx/sites/$([ "$LEVEL" = server ] \
            && echo "$FILENAME" \
            || echo "$FILENAME.d/$URL_PREFIX").conf" >/dev/null
    sudo systemctl reload nginx || sudo systemctl restart nginx \
        || ! sudo systemctl is-failed nginx >/dev/null
    ;;
esac

if "${SSL:-false}"; then
    echo "$FQDN" | grep -qF . || die "ERROR: Invalid FQDN"
    case "${HTTPD-nginx}" in
    nginx)
        if exists apt-get; then
            sudo apt-get install -yq software-properties-common
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get install -yq certbot python3-certbot-nginx
        elif exists pacman; then
            sudo pacman -qS --needed --noconfirm certbot-nginx
        fi
        if sudo test ! -d "/etc/letsencrypt/live/$FQDN"; then
            sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
                -m "root@$FQDN" -d "$FQDN" --cert-name "$FQDN"
        fi
        sudo certbot install -n --nginx --reinstall -d "$FQDN" \
            --cert-name "$FQDN"
        <"/etc/nginx/sites/$FILENAME.conf" \
            sed 's/\(443\|'"${PORT:-443}"'\) ssl\( http2\|\);/'"$(
                    )${PORT:-443}"' ssl http2;/' \
                | sponge "/etc/nginx/sites/$FILENAME.conf"
        sudo systemctl enable --now certbot-renew.timer
        ;;
    *)
        die "ERROR: SSL installation not implemented for $HTTPD"
        ;;
    esac
    sudo systemctl reload nginx || sudo systemctl restart nginx || true
fi
