#!/usr/bin/env sh
#airplay - install shairport-sync and set it up
set -eux

sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; sudo cp "$2" "$1"; rm "$2"; }
prepend() {
    if ! <"$1" grep -qxF "$2"; then
        { echo "$2"; cat "$1"; } | sponge "$1"
    fi
}

SINK_TYPE="${SINK_TYPE-pipewire}"

if </proc/cpuinfo grep -q '^Model.*Raspberry Pi 3'; then
    prepend /boot/config.txt 'dtparam=audio=on'
    prepend /boot/config.txt 'dtoverlay=pisound'
fi

#Install shairport-sync usable development version
(
    cd airplay
    makepkg -si --noconfirm --needed --asdeps -p nqptp.PKGBUILD
    makepkg -si --noconfirm --needed -p shairport-sync.PKGBUILD
)

ALSA_MIXER=Master
MPRIS_SERVICE_BUS=session
case "$SINK_TYPE" in
alsa)
    MPRIS_SERVICE_BUS=system
    if [ -n "${ALSA_DEVICE-}" ]; then
        <"airplay/asound.conf" \
            sed \
                -e "s/\\\$ALSA_DEVICE/$ALSA_DEVICE/" \
            | sudo tee "/etc/asound.conf" >/dev/null
        ALSA_MIXER=PCM
    fi
    sudo pacman --needed --noconfirm -qS alsa-utils
    sudo mkdir -p /etc/mpv
    sudo cp airplay/mpv.conf /etc/mpv/mpv.conf
    sudo cp airplay/input.conf /etc/mpv/input.conf
    ;;
esac

<"airplay/shairport-sync.conf" \
    sed \
        -e "s/\\\$ALSA_MIXER/$ALSA_MIXER/" \
        -e "s/\\\$MPRIS_SERVICE_BUS/$MPRIS_SERVICE_BUS/" \
    | sudo tee "/etc/shairport-sync.conf" >/dev/null

if [ "$SINK_TYPE" = alsa ]; then
    sudo systemctl enable shairport-sync nqptp
    sudo systemctl restart shairport-sync nqptp
fi
