#!/usr/bin/env sh
set -eux

in_dir() (cd "$1" && shift && "$@")

lineinfile() {
	sudo grep -qxF "$2" "$1" || echo "$2" | sudo tee -a "$1" >/dev/null
}

download() { #1: url, 2: path
	if [ -e "$2" ]; then
		sudo curl -fLo "$2" -z "$2" "$1"
	else
		sudo curl -fLo "$2" "$1"
	fi
}

sudo pacman --needed --noconfirm -qS ffmpeg
download "https://github.com/AlexxIT/go2rtc/releases/latest/download/$(
)go2rtc_linux_arm64" /usr/local/bin/go2rtc
sudo chmod +x /usr/local/bin/go2rtc

printf %s 'u! go2rtc video' | sudo systemd-sysusers -
sudo cp camera/go2rtc.service /etc/systemd/system/go2rtc.service

<camera/go2rtc.yaml sed \
	-e "s|\\\$VIDEO_DEVICE|$VIDEO_DEVICE|" \
	| sudo tee /etc/go2rtc.yaml >/dev/null

sudo systemctl daemon-reload
sudo systemctl enable go2rtc

if [ -z "${HARDWARE-}" ] && </proc/cpuinfo grep -Eq "Raspberry Pi Zero"; then
	if ! grep -qxF "gpu_mem=16" /boot/config.txt; then
		echo "gpu_mem=16" | sudo tee -a /boot/config.txt
		sudo systemctl reboot --when=+0s
		exit 0
	fi
fi

sudo systemctl restart go2rtc
