#!/usr/bin/env sh
set -eu

# shellcheck source=../override.sh
. "$PREFIX/lib/sh/override.sh"

save() {
	for x; do
		printf %s\\n "$x" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"
	done
	echo " "
}

eval "set -- $(save "$@" | sed "s/'--clipboard'/'--clipboard-mode'/")"
exec "$(command_without_override VBoxManage)" "$@"
