#!/usr/bin/env sh
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if ! id -u homebridge >/dev/null 2>&1; then
    sudo useradd -s /bin/false -m homebridge
fi

exists homebridge || yay --needed --noconfirm -qS homebridge qrencode
sudo pacman --needed --noconfirm -qS qrencode
sudo npm install -g homebridge-mqttthing
sudo tee /etc/systemd/system/homebridge.service >/dev/null <<"EOF"
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
Environment=
Environment=HOMEBRIDGE_OPTS="-I -U /srv/homebridge"
Environment=UIX_STORAGE_PATH="/srv/homebridge"
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
EOF

sudo mkdir -p /srv/homebridge

HOMEBRIDGE_USER="${HOMEBRIDGE_USER-$(</dev/urandom \
    tr -dc A-F0-9 \
    | head -c 12 \
    | sed 's/\(..\)\(..\)\(..\)\(..\)\(..\)\(..\)/\1:\2:\3:\4:\5:\6/')}"
HOMEBRIDGE_PIN="${HOMEBRIDGE_PIN-$(</dev/urandom \
    tr -dc 0-9 \
    | head -c 8 \
    | sed 's/\(...\)\(..\)\(...\)/\1-\2-\3/')}"

[ -e /srv/homebridge/config.json ] \
    || sudo tee /srv/homebridge/config.json >/dev/null <<EOF
{
  "bridge": {
    "name": "$(uname -n)",
    "username": "$HOMEBRIDGE_USER",
    "port": 51616,
    "pin": "$HOMEBRIDGE_PIN"
  },
  "accessories": [],
  "platforms": []
}
EOF

sudo cp homebridge/tasmota.js /srv/homebridge/tasmota.js
sudo chown -R homebridge:homebridge /srv/homebridge

sudo systemctl enable homebridge
sudo systemctl restart homebridge

for x in `seq 1 100`; do
    ! [ -e /srv/homebridge/persist ] || break
    sleep 1
done

echo '
    const fs = require("fs");
    const config = JSON.parse(fs.readFileSync("config.json"));
    const category = 2; //Bridge
    const pin = parseInt(config.bridge.pin.replace(/-/g, ""), 10);

    const buffer = new DataView(new ArrayBuffer(8));
    buffer.setUint32(0, category >> 1);
    buffer.setUint32(4, ((category & 1) << 7) | 1 << 28 | pin);
    const code = (buffer.getUint32(4) + buffer.getUint32(0) * Math.pow(2, 32))
        .toString(36)
        .toUpperCase()
        .padStart(9, "0");

    const { setupID } = JSON.parse(fs.readFileSync(`persist/AccessoryInfo.${
        config.bridge.username.replace(/:/g, "")}.json`));

    console.log(`X-HM://${code}${setupID}`);
' | (cd /srv/homebridge; sudo -u homebridge node -) | qrencode -t ANSI -o -
