name: searxng
services:
    searxng:
        image: searxng/searxng
        restart: unless-stopped
        ports:
            - $PORT:8080
        volumes:
            - /etc/searxng:/etc/searxng
        environment:
            - BASE_URL=$BASE_URL
            - INSTANCE_NAME=$INSTANCE_NAME
