#!/usr/bin/env sh
#searxng - install and configure metasearch engine
set -eu

install_docker_conf() ( #1: project_name
	if [ "$(uname -s)" = Linux ]; then
		conf_root="/etc"
	elif [ "$(uname -s)" = Darwin ]; then
		conf_root="$XDG_CONFIG_HOME"
		sudo() { "$@"; }
	fi
	sudo mkdir -p "$conf_root/compose/$1"
	cd "$conf_root/compose/$1"
	sudo tee "compose.yaml" >/dev/null
	sudo docker compose up -d --remove-orphans
)

sudo systemd-tmpfiles --create - <<-EOF
	f+~ /etc/searxng/settings.yml - - - - $(
		{ sed s/^.// | base64 -w0; } <<-CONFIG
			.use_default_settings: true
			.server:
			.  secret_key: "$SEARXNG_SECRET"
			.  image_proxy: true
			.search:
			.  formats: [html, csv, json, rss]
		CONFIG
	)
EOF

<searxng/compose.yaml sed \
	-e "s|\\\$BASE_URL|$BASE_URL|g" \
	-e "s|\\\$INSTANCE_NAME|$INSTANCE_NAME|g" \
	-e "s|\\\$PORT|$PORT|g" \
	| install_docker_conf searxng
