[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "alacritty"

[font]
size = 9.0

[keyboard]
bindings = [
    { mods = "Alt", key = "C", action = "Copy" },
    { mods = "Alt", key = "V", action = "Paste" },
    { mods = "Alt", key = "W", action = "Quit" },
    { mods = "Alt", key = "Q", action = "Quit" },
    { mods = "Alt", key = "N", action = "CreateNewWindow" },
]

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Middle", action = "PasteSelection" },
]

[scrolling]
history = 10000
multiplier = 10

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0

[window.padding]
x = 2
y = 2
