[colors.bright]
black = "0xb8b8b8"
blue = "0x585858"
cyan = "0xa16946"
green = "0xe8e8e8"
magenta = "0x282828"
red = "0xdc9656"
white = "0x181818"
yellow = "0xd8d8d8"

[colors.normal]
black = "0xf8f8f8"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0x383838"
yellow = "0xf7ca88"

[colors.primary]
background = "0xf8f8f8"
foreground = "0x383838"
