#!/usr/bin/env sh
#add_tunnel_user - create nologin tunnel user
set -eu

printf %s 'u tunnel - - /usr/share/tunnel' | sudo systemd-sysusers -
sudo mkdir -p /usr/share/tunnel/.ssh
sudo chown -R tunnel /usr/share/tunnel
sudo chmod -R og-rwxs /usr/share/tunnel
