#!/usr/bin/env sh
#GTK4 applications
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
#GTK3, and Firefox. Requires gnome-themes-extra
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
