#!/usr/bin/env sh
set -eu

moveable_name() { #1 mail
    set -- "$(basename "$1")"
    echo "${1%%,U=*}$(expr "$1" : '[^:]*\(:2,[DFPRST]*\)')"
}

<"$XDG_CONFIG_HOME/isyncrc" sed -n 's/^Account //p' \
    | while read -r account; do
        mkdir -p "$NOTMUCH_DATABASE/$account"
    done

notmuch search --output=files tag:deleted and not path:/\\/Trash\\// \
    | while IFS= read -r f; do
        [ -f "$f" ] || continue
        mv "$f" "${f%${f#$NOTMUCH_DATABASE/*/}}Trash/cur/$(moveable_name "$f")"
    done
mbsync -a
