#!/usr/bin/env sh
set -eu

#MBSYNCRC should be exported from mail_client

moveable_name() { #1 mail
    set -- "$(basename "$1")"
    echo "${1%%,U=*}$(expr "$1" : '[^:]*\(:2,[DFPRST]*\)')"
}

notmuch search --output=files tag:deleted and not folder:/Trash/ \
    | while IFS= read -r f; do
        mv "$f" "${f%${f#$NOTMUCH_DATABASE/*/}}Trash/cur/$(moveable_name "$f")"
    done
mbsync -ac "$MBSYNCRC"
