#!/usr/bin/env sh
set -eu

moveable_name() { #1 mail
    set -- "$(basename "$1")"
    echo "${1%%,U=*}$(expr "$1" : '[^:]*\(:2,[DFPRST]*\)')"
}

notmuch search --output=files tag:deleted and not path:/\\/Trash\\// \
    | while IFS= read -r f; do
        [ -f "$f" ] || continue
        mv "$f" "${f%${f#$NOTMUCH_DATABASE/*/}}Trash/cur/$(moveable_name "$f")"
    done
if [ "$({ v="$(mbsync --version)" && printf '%s\n%s\n' ${v#isync } 1.5; } \
    | sort -n | head -n 1)" = 1.5 ]; then
    mbsync -a
else
    mbsync -ac "$XDG_CONFIG_HOME/mbsyncrc"
fi
