#!/usr/bin/env sh
#init - create user, only secure ssh access, install package managers and sudo
set -eu

die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
exists() { command -v "$1" >/dev/null 2>&1; }
getsh() { command -v zsh || command -v bash || command -v ash || echo sh; }
in_chroot() { ! [ / -ef /proc/1/root ]; }
lineinfile() {
	sudo grep -qxF "$2" "$1" || echo "$2" | sudo tee -a "$1" >/dev/null
}
[ $(id -u) -ne 0 ] || sudo() { "$@"; } #just run as root
rndpasswd() {
	{ LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 2>/dev/null || :; } \
		| head -c64 \
		| sed p \
		| sudo passwd "${1:-root}" >/dev/null 2>&1 \
		|| die "Can't lock password for ${1:-root}"
}

#Initialize package managers
case "$(uname -s)" in
Darwin)
	URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
	if ! exists brew; then
		bash -c "$(curl -fsSL "$URL")" || die "Homebrew installation failed"
	fi
	;;
Linux)
	if exists apk; then
		sudo apk update
	elif exists apt-get; then
		sudo apt-get update
	elif exists opkg; then
		sudo opkg update
	elif exists pacman; then
		sudo pacman-key --init
		sudo pacman-key --populate \
			"archlinux$(uname -m | sed -n 's/\(armv[67]l\|aarch64\)/arm/p')"
		sudo sed -i '/ParallelDownloads/s/^#//g' /etc/pacman.conf
		sudo pacman --noconfirm --needed -qSyu
	fi
	;;
esac

#Create user
if ! </etc/group grep -q '^mil:' || ! id -u mil >/dev/null 2>&1; then
	if exists opkg; then
		sudo opkg install shadow-useradd shadow-groupadd
	elif exists uci && exists apk; then
		sudo apk add -q shadow-useradd shadow-groupadd
	fi
	PATH="$PATH:/usr/sbin"
fi
if ! id -u mil >/dev/null 2>&1; then
	if exists useradd; then
		sudo grep -q '^wheel:' /etc/group || sudo groupadd wheel \
			|| die "Can't add user to wheel"
		sudo useradd -G wheel -s "$(getsh)" -m mil
	elif exists adduser; then
		sudo adduser -G wheel -s "$(getsh)" -D mil
	fi
	id -u mil >/dev/null 2>&1 || die "Can't add user mil"
	rndpasswd mil
fi

#Copy ssh public key and fix all permissions
sudo mkdir -p ~mil/.ssh
sudo tee ~mil/.ssh/authorized_keys >/dev/null <<EOF
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVYVOzQIykoByW8dN5uqKGUOETEUo/VP40Y704+G$(
)z0i cardno:20_109_196
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJw5nOtn9Tf4Su52fuSAdvGAsbfLJ5cietFBIrA+x$(
)ws6 cardno:33_886_248
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBBH6oWkN2W0ZcTz8ZRjwSJ7VWTR66Fqw3t1yX3nT$(
)qgR iPhone15Pro
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEf2rEZOlqUOf/hvf0SFC6yFgHwZWWNfGgI4n+EG4$(
)QCb backup
EOF
for own in mil:mil mil:staff mil:wheel mil:; do
	if </etc/group grep -q "^${own#*:}"; then #succeeds when group is empty
		if
			[ "$(ls -lnd ~mil/.ssh | awk '{ print $3 }')" -ne "$(id -u mil)" ]
		then
			sudo chown -R "${own%:}" ~mil
			sudo chmod -R og-rwxs ~mil
		fi
		break
	fi
done

#Ensure continuous access: install sudo/doas+sshd, configure, check, commit
if exists apt-get; then
	sudo env DEBIAN_FRONTEND=noninteractive apt-get -yq install \
		openssh-server sudo
elif exists uci; then
	sudo rm -f /etc/banner
	if exists opkg; then
		sudo opkg install sudo openssh-sftp-server
	elif exists apk; then
		sudo apk add sudo openssh-sftp-server
		sudo uci set attendedsysupgrade.client.login_check_for_upgrades='1'
	fi
elif exists apk; then
	if apk query doas-sudo-shim | grep -q .; then
		sudo apk -q add openssh doas doas-sudo-shim
	else
		sudo apk -q add openssh doas
		printf '#!/bin/sh\nexec doas "$@"\n' \
			| sudo tee "/usr/bin/sudo" >/dev/null
		sudo chmod +x "/usr/bin/sudo"
	fi
elif exists apt-get; then
	sudo apt-get install -qy openssh-server sudo
elif exists pacman; then
	sudo pacman --needed --noconfirm -qS openssh sudo
fi

if exists doas; then
	lineinfile /etc/doas.conf 'permit nopass :wheel'
	lineinfile /etc/doas.conf 'permit nopass keepenv root'
elif (
	unset -f sudo 2>/dev/null || :
	exists sudo \
		&& lineinfile /etc/sudoers "%$(
			[ "$(uname -s)" = Darwin ] && echo admin || echo wheel
		) ALL=(ALL) NOPASSWD: ALL" \
		&& sudo true to check access
); then
	: "sudo setup success"
else
	die "sudo setup failed"
fi

if exists uci; then
	sudo uci set 'dropbear.@dropbear[0].RootPasswordAuth=off'
	sudo uci set 'dropbear.@dropbear[0].PasswordAuth=off'
	sudo uci commit dropbear
	sudo /etc/init.d/dropbear restart
else
	printf %s\\n \
		'PermitRootLogin no' \
		'AuthorizedKeysFile .ssh/authorized_keys' \
		'PasswordAuthentication no' \
		'ChallengeResponseAuthentication no' \
		"$(
			sudo sshd -T 2>/dev/null | grep -iq UsePAM \
				&& echo 'UsePAM yes' || :
		)" \
		"$(
			if [ "$(uname -s)" = Darwin ]; then
				echo 'Subsystem sftp internal-sftp'
			elif [ -e /usr/lib/openssh/sftp-server ]; then
				echo 'Subsystem sftp /usr/lib/openssh/sftp-server'
			elif [ -e /usr/lib/ssh/sftp-server ]; then
				echo 'Subsystem sftp /usr/lib/ssh/sftp-server'
			fi
		)" \
		'PrintMotd no' \
		'GatewayPorts yes' \
		'StreamLocalBindUnlink yes' \
		'AcceptEnv TERM_PROGRAM' \
		| sudo tee /etc/ssh/sshd_config >/dev/null

	if [ "$(uname -s)" = Darwin ]; then
		sudo systemsetup -f -setremotelogin on
	elif grep -iq microsoft /proc/version 2>/dev/null; then
		[ -n "${SSH_CONNECTION-}" ] || sudo pkill sshd || :
		sudo mkdir -p /run/sshd
		sudo ssh-keygen -A
		sudo /usr/sbin/sshd -p 23 #daemon is managed in Windows
	elif exists rc-update; then
		sudo rc-update add sshd
		sudo rc-service sshd restart
	elif exists systemctl; then
		if ! in_chroot; then
			ssh_service="$(
				systemctl list-unit-files \
					| sed -En '/alias/d;s/^(sshd?).service\s.*/\1/p'
			)"
			sudo systemctl enable --now "$ssh_service"
			sudo systemctl reload "$ssh_service"
		else
			sudo systemctl enable sshd
		fi
	fi
fi

(ps -A 2>/dev/null || ps) | grep -Eq '([s]shd|[d]ropbear)' \
	|| in_chroot \
	|| die "ssh setup failed"

#Set hostname
if [ -n "${NEWHOSTNAME-}" ]; then
	HOSTNAME="$NEWHOSTNAME"
else
	HOSTNAME="${HOSTNAME-$(uname -n)}"
fi
if ! expr localhost = "$HOSTNAME" \| "$HOSTNAME" : '[0-9.]*$' >/dev/null; then
	echo "$HOSTNAME" | sed 's/\..*//' | sudo tee /etc/hostname >/dev/null
	if [ "$(uname -s)" = Darwin ]; then
		for name in HostName LocalHostName ComputerName; do
			sudo scutil --set "$name" "$HOSTNAME"
		done
		sudo dscacheutil -flushcache
	elif exists uci; then
		sudo uci set "system.@system[0].hostname=$HOSTNAME"
		sudo uci commit system
	elif
		! in_chroot && exists hostname \
			&& hostname --help 2>&1 | grep -qe '-F FILE'
	then
		hostname -F /etc/hostname
	elif [ -d /etc/conf.d ]; then
		echo "hostname='$HOSTNAME'" | sudo tee /etc/conf.d/hostname >/dev/null
	fi
	if [ -f /etc/dhcpcd.conf ]; then
		lineinfile /etc/dhcpcd.conf hostname
	fi
fi

if exists systemctl && systemctl is-enabled -q systemd-resolved; then
	sudo mkdir -p "/etc/systemd/resolved.conf.d/"
	printf '[Resolve]\nResolveUnicastSingleLabel=yes\n' \
		| sudo tee /etc/systemd/resolved.conf.d/resolve-lan.conf >/dev/null
fi

#Remove set-up user
if id -u alarm >/dev/null 2>&1; then
	sudo userdel -f alarm >/dev/null 2>&1
fi
