#!/usr/bin/env sh
#install_arch - install arch, run as root
set -eux

sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; mv "$2" "$1"; }

cpu_manufacturer() {
    cat /proc/cpuinfo \
        | sed -n '/AuthenticAMD/{s/.*/amd/p;q};/GenuineIntel/{s/.*/intel/p;q}'
}

echo io >/etc/hostname
echo 'en_US.UTF-8 UTF-8' >/etc/locale.gen
locale-gen
ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
hwclock --systohc
PART="$(df -P / | awk 'END { print $1 }')"
DISK="/dev/$(lsblk -no pkname "$PART")"
UUID="$(lsblk -no UUID "$PART")"
PARTUUID="$(lsblk -no PARTUUID "$PART")"
genfstab -Upf "$DISK" / >/etc/fstab
echo 'nameserver 8.8.8.8' >/etc/resolv.conf
pacman --needed --noconfirm -qS dhcpcd netctl dialog wpa_supplicant
systemctl enable dhcpcd
if "${LIVEUSB:-false}"; then
    </etc/mkinitcpio.conf \
        sed '/^HOOKS/{
            s/block //;s/keyboard //;s/autodetect /block keyboard &/}' \
        | sponge /etc/mkinitcpio.conf
    mkinitcpio -p linux
    pacman --needed --noconfirm -qS syslinux
    mkdir -p /boot/EFI/syslinux
    cp -r /usr/lib/syslinux/efi64/* /boot/EFI/syslinux/
    [ -d /boot/EFI/boot ] || mv /boot/EFI/syslinux /boot/EFI/boot
    cp /boot/EFI/boot/syslinux.efi /boot/EFI/boot/bootx64.efi
    </boot/syslinux/syslinux.cfg \
        sed \
            -e "s_root=/dev/[^ ]*_root=UUID=${UUID}_" \
            -e "s_INITRD _INITRD ../amd-ucode.img,../intel-ucode.img,_" \
        | sponge /boot/syslinux/syslinux.cfg
else
    pacman --needed --noconfirm -qS "$(cpu_manufacturer)-ucode" efibootmgr
    efibootmgr --disk "$DISK" --part 1 --create \
        --label "Arch Linux" --loader /vmlinuz-linux \
        --unicode "root=PARTUUID=$PARTUUID rw `:\
        `initrd=\\$(cpu_manufacturer)-ucode.img `:\
        `initrd=\\initramfs-linux.img" --verbose
fi
