#!/usr/bin/env sh
set -eu

sponge() { set -- "$1" "$(mktemp)" && cat >"$2" && sudo mv "$2" "$1"; }

sudo pacman --needed --noconfirm -S mariadb

MYSQLROOT="${MYSQLROOT-/srv/mysql}"
</etc/my.cnf.d/server.cnf sed \
    -e '/^datadir=/d;/\[mysqld\]/adatadir='"$MYSQLROOT"'' \
    | sponge /etc/my.cnf.d/server.cnf
[ -d "$MYSQLROOT" ] \
    || sudo mariadb-install-db --user=mysql --basedir=/usr \
        --datadir="${MYSQLROOT}"

sudo systemctl enable --now mariadb
