#!/usr/bin/env sh
set -eux

sudo pacman --needed --noconfirm -qS miniflux

sudo mkdir -p /etc/systemd/system/miniflux.service.d
printf '[Service]\nRuntimeDirectory=miniflux\n' \
    | sudo tee /etc/systemd/system/miniflux.service.d/override.conf >/dev/null
sudo systemctl daemon-reload

sudo tee /etc/miniflux.conf >/dev/null <<EOF
LISTEN_ADDR=/run/miniflux/miniflux.sock
BASE_URL=${BASE_URL-http://localhost/}
DATABASE_URL=$DATABASE_URL
RUN_MIGRATIONS=1
CREATE_ADMIN=1
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF
sudo systemctl enable miniflux && sudo systemctl restart miniflux
