#!/usr/bin/env sh
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if exists apk; then
	sudo apk -q add miniflux
elif exists pacman; then
	sudo pacman --needed --noconfirm -qS miniflux
fi

sudo systemd-tmpfiles --create - <<-EOF
	f+~ /etc/miniflux.conf - - - - $(
		{ base64 | tr -d '\n'; } <<-CONF
			LISTEN_ADDR=/run/miniflux/miniflux.sock
			BASE_URL=${BASE_URL-http://localhost/}
			DATABASE_URL=$DATABASE_URL
			RUN_MIGRATIONS=1
			CREATE_ADMIN=1
			ADMIN_USERNAME=$ADMIN_USERNAME
			ADMIN_PASSWORD=$ADMIN_PASSWORD
		CONF
	)
EOF
if ! id -Gn http 2>/dev/null | grep -q miniflux; then
	echo 'm http miniflux' | sudo systemd-sysusers -
	sudo systemctl restart nginx
fi

if exists rc-service; then
	rc-update -q add radicale default
	rc-service -q radicale restart
elif exists systemctl; then
	sudo systemd-tmpfiles --create - <<-EOF
		f+~ /etc/systemd/system/miniflux.service.d/override.conf - - - - $(
			{ base64 | tr -d '\n'; } <<-OVERRIDE
				[Service]
				RuntimeDirectory=miniflux
			OVERRIDE
		)
	EOF
	sudo systemctl daemon-reload
	sudo systemctl enable miniflux && sudo systemctl restart miniflux
fi
