#!/usr/bin/env sh
set -eu

sudo pacman --needed --noconfirm -qS miniflux

sudo systemd-tmpfiles --create - <<-EOF
	f+~ /etc/miniflux.conf - - - - $(
		{ base64 | tr -d '\n'; } <<-CONF
			LISTEN_ADDR=/run/miniflux/miniflux.sock
			BASE_URL=${BASE_URL-http://localhost/}
			DATABASE_URL=$DATABASE_URL
			RUN_MIGRATIONS=1
			CREATE_ADMIN=1
			ADMIN_USERNAME=$ADMIN_USERNAME
			ADMIN_PASSWORD=$ADMIN_PASSWORD
		CONF
	)
	f+~ /etc/systemd/system/miniflux.service.d/override.conf - - - - $(
		{ base64 | tr -d '\n'; } <<-OVERRIDE
			[Service]
			RuntimeDirectory=miniflux
		OVERRIDE
	)
EOF
sudo systemctl daemon-reload
sudo systemctl enable miniflux && sudo systemctl restart miniflux
