#!/usr/bin/env sh
#postgresql - install and configure postgresql
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
isWsl() { grep -iq microsoft /proc/version 2>/dev/null; }

#Try becoming postgres with sudo to avoid the password
dbdo() (
	[ -n "${DBUSER-}" ] || [ "$(uname -s)" = Darwin ] || isWsl \
		|| set -- sudo -u postgres "$@"
	cd /
	"$@"
)

if exists apk; then
	sudo apk -q add postgresql
elif exists brew; then
	PACKAGE=postgresql@18
	brew install "$PACKAGE"
	brew link "$PACKAGE"
	brew services start "$PACKAGE"
	return 0
elif exists pacman; then
	sudo pacman --needed --noconfirm -qS postgresql
fi

PGROOT="${PGROOT:-/srv/postgresql}"
sudo systemd-tmpfiles --create - <<-EOF
	f+~ /etc/systemd/system/postgresql.service.d/pgroot.conf - - - - $(
		{ base64 | tr -d '\n'; } <<-CONF
			[Service]
			Environment=PGROOT=$PGROOT
		CONF
	)
	d   "$PGROOT" 0750 postgres wheel
	Z   "$PGROOT" 0750 postgres wheel
EOF

if ! sudo test -f "$PGROOT/data/PG_VERSION"; then
	dbdo initdb --locale=en_US.UTF-8 -E UTF8 -D "$PGROOT/data"
fi

if exists rc-service; then
	rc-update -q add postgresql default
	rc-service -q postgresql start
elif exists systemctl; then
	sudo systemctl enable --now postgresql
fi
