#!/usr/bin/env sh
set -eux

#This script might need to be run first if there is no internet yet
[ $(id -u) = 0 ] && sudo() { "$@"; } || true #just run as root

if sudo uci show 'network.@switch_vlan[0]' >/dev/null 2>&1; then
    #Bridge all ethernet interfaces
    BRIDGE_PORTS="$(sudo uci show network \
        | sed -n "s/network.@switch_vlan.*ports='\\(.*\\)'/\\1/p" \
        | tr ' ' '\n' \
        | sort -u \
        | tr '\n' ' ')"
    BRIDGE_CONFIG="$(sudo uci show 'network.@switch_vlan[0]')"

    while sudo uci delete 'network.@switch_vlan[0]' 2>/dev/null; do :; done

    BRIDGE_RULE_NAME="$(sudo uci add network switch_vlan)"
    echo "$BRIDGE_CONFIG" \
        | sed \
            -e "s/cfg[^.=]*/$BRIDGE_RULE_NAME/" \
            -e "/ports=/s/'.*'/'$BRIDGE_PORTS'/" \
            -e "s/^/set /" \
        | sudo uci batch
elif grep -sq DEVTYPE=dsa /sys/class/net/*/uevent; then
    #Bit of a hack
    sudo uci add_list 'network.@device[0].ports'='wan'
    #BRIDGE_PORTS="$(ip a show | sed -n 's/[0-9]*: \([^ ]*\)@.*/\1/p')"
    #BRIDGE_CONFIG="$(sudo uci show 'network.lan')"
    uci del dhcp.lan.ra
    uci del dhcp.lan.ra_slaac
    uci del dhcp.lan.ra_flags
    uci del dhcp.lan.dhcpv6
else
    echo "Don't know how to bridge networks"
    false
fi

sudo uci delete network.wan
sudo uci delete network.wan6

#Enable dhcp client
sudo uci set network.lan.proto=dhcp

#Disable services
sudo /etc/init.d/dnsmasq disable
sudo /etc/init.d/dnsmasq stop
sudo /etc/init.d/odhcpd disable
sudo /etc/init.d/odhcpd stop
sudo /etc/init.d/firewall disable
sudo /etc/init.d/firewall stop

#Commit and reload
sudo uci commit
sudo /etc/init.d/network reload
sudo uci delete network.wan6
