#!/usr/bin/env sh
# shellcheck disable=SC2016,SC1003
set -eu

pacman --needed --noconfirm -qS socat

sudo systemd-tmpfiles --create - <<-EOF
	f+~ /etc/systemd/system/tunnel@.service - - - - $(
		{ base64 | tr -d '\n'; } <<-SERVICE
			[Unit]
			Description=TCP tunnel
			After=network.target

			[Service]
			User=root

			ExecStart=/bin/sh -c '\
				hostname="%i"; \
				port="${hostname#*:}"; \
				hostname="${hostname%:$port}"; \
				exec socat "TCP4-LISTEN:$port,reuseaddr,fork" \
				"TCP4:$hostname:$port"; \
			'
			Restart=always
			RestartSec=5
			StartLimitBurst=
			StartLimitIntervalSec=60

			[Install]
			WantedBy=multi-user.target
		SERVICE
	)
EOF

sudo systemctl daemon-reload
sudo systemctl enable "tunnel@$FORWARDSPEC"
sudo systemctl restart "tunnel@$FORWARDSPEC"
