#!/usr/bin/env sh
#ssl - set up certificate for site
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; sudo mv "$2" "$1"; }

if exists apt-get; then
    sudo apt-get install -yq software-properties-common
    sudo add-apt-repository universe
    sudo apt-get update
    sudo apt-get install -yq certbot python3-certbot-nginx
elif exists pacman; then
    sudo pacman -qS --needed --noconfirm certbot-nginx
fi
FILENAME="$FQDN${HTTP_PORT+:$HTTP_PORT}"
PORT="${PORT-443}"
echo "$FQDN" | grep -qF . || { echo "ERROR: Invalid FQDN"; exit 1; }
if sudo test ! -d "/etc/letsencrypt/live/$FQDN"; then
    sudo certbot certonly -n --nginx --agree-tos --no-eff-email \
        -m "root@$FQDN" -d "$FQDN" --cert-name "$FQDN"
fi
sudo certbot install -n --nginx --reinstall -d "$FQDN" --cert-name "$FQDN"
<"/etc/nginx/sites/$FILENAME.conf" \
    sed 's/\(443\|'"$PORT"'\) ssl\( http2\|\);/'"$PORT"' ssl http2;/' \
    | sponge "/etc/nginx/sites/$FILENAME.conf"

sudo systemctl reload nginx
sudo systemctl enable --now certbot-renew.timer
