#!/usr/bin/env sh
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

if [ "$(uname -s)" = Darwin ]; then
	if ! [ -d /Applications/Tailscale.app ]; then
		printf "Install Tailscale using App Store and rerun\n" >&2
		open -a "App Store"
		exit 1
	else
		open -a Tailscale
	fi
	printf %s\\n \
		'#!/usr/bin/env sh' \
		'/Applications/Tailscale.app/Contents/MacOS/Tailscale "$@"' \
		>"${XDG_BIN_HOME-$HOME/.local/bin}/tailscale"
	chmod +x "${XDG_BIN_HOME-$HOME/.local/bin}/tailscale"
	tailnetsuffix="$(tailscale status --json | jq -r .MagicDNSSuffix)"
	sudo mkdir -p /etc/resolver/
	printf %s\\n \
		"domain $tailnetsuffix" \
		"search $tailnetsuffix" \
		| sudo tee /etc/resolver/tailscale >/dev/null
	sudo killall -HUP mDNSResponder
elif [ "$(uname -s)" = Linux ]; then
	if exists pacman; then
		sudo pacman --needed --noconfirm -qS tailscale
	else
		curl -fsSL https://tailscale.com/install.sh | sh
	fi
	sudo systemctl enable --now tailscaled
	printf %s\\n \
		'[Unit]' \
		'Description=Disable offloading on tailscale0' \
		'After=network-online.target tailscaled.service' \
		'Wants=network-online.target' \
		'' \
		'[Service]' \
		'Type=oneshot' \
		'ExecStart=/sbin/ethtool -K tailscale0 tso off gso off gro off' \
		'' \
		'[Install]' \
		'WantedBy=multi-user.target' \
		| sudo tee /etc/systemd/system/tailscale-offload-fix.service >/dev/null
	sudo systemctl daemon-reload
	sudo tailscale up
	sudo systemctl enable --now tailscale-offload-fix
fi
