#!/usr/bin/env sh
#user - create user
set -eu

echo() { printf "%s\n" "$*"; }
exists() { command -v "$1" >/dev/null 2>&1; }
die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
get_user_home() { eval "echo ~$(echo "$1" | sed 's/[^-A-Za-z0-9.]/\\&/g')"; }

rndpasswd() {
    LC_CTYPE=C </dev/urandom tr -cd A-Za-z0-9 \
        | head -c64 \
        | sed p \
        | sudo passwd "${1:-root}" >/dev/null 2>&1 \
        || die "Can't lock password for ${1:-root}"
}

USER_SHELL="${USER_SHELL:-/bin/false}"

if ! id -u "$USER_NAME" >/dev/null 2>&1; then
    PATH="$PATH:/usr/sbin"
    set -- -m -s "$(command -v "$USER_SHELL")" "$USER_NAME"
    [ -z "${USER_HOME:-}" ] || set -- -d "$USER_HOME" "$@"
    if exists useradd; then
        sudo useradd "$@"
    elif exists adduser; then
        sudo adduser "$@"
    fi
else
    sudo chsh -s "$USER_SHELL" "$USER_NAME"
    [ -z "${USER_HOME:-}" ] || sudo usermod -md "$USER_HOME"
fi
rndpasswd "$USER_NAME"

if [ -n "${USER_PUBKEY:-}" ] && [ -d "$(get_user_home "$USER_NAME")" ]; then
    sudo mkdir -p "$(get_user_home "$USER_NAME")/.ssh"
    echo "$USER_PUBKEY" \
        | sudo tee "$(get_user_home "$USER_NAME")/.ssh/authorized_keys" \
            >/dev/null
    sudo chown -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
    sudo chown "$USER_NAME" "$(get_user_home "$USER_NAME")"
    if getent group "$USER_NAME" >/dev/null \
        || </etc/group grep -q "^$USER_NAME:"; then
        sudo chgrp -R "$USER_NAME" "$(get_user_home "$USER_NAME")/.ssh"
        sudo chgrp "$USER_NAME" "$(get_user_home "$USER_NAME")"
    fi
    sudo chmod -R og-rwxs "$(get_user_home "$USER_NAME")/.ssh"
    sudo chmod og-rwxs "$(get_user_home "$USER_NAME")"
fi
