#!/usr/bin/env sh
#fileserver - installs samba and configuration

exists() { command -v "$1" >/dev/null 2>&1; }

if exists apk; then
	apk -q add samba
elif exists pacman; then
	sudo pacman -q --noconfirm -S --needed samba
fi

sudo systemd-tmpfiles --create - <<EOF
C /etc/samba/smb.conf      - - - - $PWD/fileserver/smb.conf
f /etc/samba/includes.conf - - - -
EOF

if exists rc-service; then
	rc-update -q add samba default
	rc-service -q samba start
elif exists systemctl; then
	sudo systemctl enable smb nmb
	sudo systemctl restart smb nmb
fi
