#!/usr/bin/env sh
#fileserver - installs samba and configuration

sudo pacman -q --noconfirm -S --needed samba

sudo systemd-tmpfiles --create - <<EOF
C /etc/samba/smb.conf      - - - - $PWD/fileserver/smb.conf
f /etc/samba/includes.conf - - - -
EOF

sudo systemctl enable smb nmb
sudo systemctl restart smb nmb
