#!/usr/bin/env sh
#fileserver - installs samba and configuration

sudo pacman -q --noconfirm -S --needed samba
sudo mkdir -p /etc/samba
sudo cp fileserver/smb.conf /etc/samba/smb.conf
sudo touch /etc/samba/includes.conf
sudo systemctl enable smb nmb
sudo systemctl restart smb nmb
