Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.define ENV["VM_NAME"]

  config.vm.network "forwarded_port", guest: 22, host: ENV["HOST_SSH_PORT"]
  config.vm.network "forwarded_port", guest: 24, host: ENV["HOST_WSSH_PORT"]
  config.vm.network "forwarded_port", guest: 3389, host: ENV["HOST_RDP_PORT"]

  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV["VM_NAME"]
    vb.memory = 6144
    vb.cpus = 2
    vb.gui = false
  end
  config.winrm.basic_auth_only = true
  config.winrm.transport = :plaintext

  config.vm.provision "shell" do |s|
    s.path = "provision.ps1"
    s.env = {
      "HOSTNAME" => ENV["VM_NAME"],
      "PUBKEY" => ENV["PUBKEY"]
    }
  end
  #config.vm.provider "virtualbox" do |vb|
  #  vb.customize ["modifyvm", :id, "--usb", "on"]
  #  vb.customize ["modifyvm", :id, "--usbehci", "on"]
  #  vb.customize ["usbfilter", "add", "0",
  #    "--target", :id,
  #    "--name", "YubiKey",
  #    "--manufacturer", "Yubico"]
  #end
end
