#!/usr/bin/env sh
#desktop - install desktop programs and configuration
set_file() ( f="$1"; shift; printf '%s\n' "$@" | sudo tee "$f" >/dev/null; )

case "$(uname -s)" in
Linux)
    sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
    set_file /etc/systemd/system/getty@tty1.service.d/override.conf \
        '[Service]' \
        'Type=simple' \
        'ExecStart=' \
        'ExecStart=-/usr/bin/agetty --skip-login --login-options "-f mil"'`
            `' --noissue --noclear %I $TERM'
    sudo mkdir -p /etc/systemd/logind.conf.d
    set_file /etc/systemd/logind.conf.d/gui.conf \
        '[Login]' \
        'HandlePowerKey=ignore' \
        'HandlePowerKeyLongPress=poweroff'
    set_file /etc/udev/rules.d/50-power-change.rules ''`
        `'ACTION=="change", SUBSYSTEM=="power_supply", '`
        `'ENV{POWER_SUPPLY_TYPE}=="Mains", RUN+="'`
        `"$(command -v sh) -l $(sudo -u mil sh -lc 'command -v gui')"`
        `' -u mil localhost swaymsg seat seat0 cursor move 0 1"'
    sudo pacman --needed --noconfirm -qS sway swaybg \
        adobe-source-sans-fonts ttf-sourcecodepro-nerd ttf-joypixels \
        xdg-desktop-portal-wlr gnome-themes-extra gammastep avahi \
        pipewire pipewire-pulse wireplumber pipewire-zeroconf gcr bluez
    sudo usermod -aG video mil
    sudo systemctl enable --now avahi-daemon
    ;;
Darwin)
    #Tap-to-click
    defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
        Clicking -bool true
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    #Style
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain AppleHighlightColor \
        "0.847059 0.847059 0.862745";
    defaults write NSGlobalDomain AppleInterfaceStyle Dark
    defaults write NSGlobalDomain AppleAquaColorVariant 6
    defaults write NSGlobalDomain _HIHideMenuBar -bool true
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock autohide-delay -float 1000
    defaults write com.apple.dock no-bouncing -bool true
    defaults write com.apple.dock mru-spaces -bool false
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder QuitMenuItem -bool true
    killall Dock Finder SystemUIServer
    defaults write com.apple.Terminal FocusFollowsMouse -string YES
    #Default software
    brew install hammerspoon pinentry-mac
    #Hammerspoon XDG
    defaults write org.hammerspoon.Hammerspoon MJConfigFile \
        "$XDG_CONFIG_HOME/hammerspoon/init.lua"
    ;;
esac
