#!/usr/bin/env sh
#desktop - install desktop programs and configuration
set_file() (f="$1" && shift && printf '%s\n' "$@" | sudo tee "$f" >/dev/null)

case "$(uname -s)" in
Linux)
	sudo pacman --needed --noconfirm -qS sway swaybg \
		adobe-source-sans-fonts ttf-sourcecodepro-nerd ttf-joypixels \
		xdg-desktop-portal-wlr gnome-themes-extra gammastep avahi \
		pipewire pipewire-pulse wireplumber pipewire-zeroconf gcr bluez
	printf %s 'm mil video' | sudo systemd-sysusers -
	sudo systemd-tmpfiles --create - <<-EOF
		f+~ /etc/systemd/system/getty@tty1.service.d/override.conf - - - - $(
			{ base64 | tr -d '\n'; } <<-CONF
				[Service]
				Type=simple
				ExecStart=
				ExecStart=-/usr/bin/agetty --skip-login --login-options \
					"-f mil" --noissue --noclear %I $TERM
			CONF
		)
		f+~ /etc/systemd/logind.conf.d/gui.conf - - - - $(
			{ base64 | tr -d '\n'; } <<-CONF
				[Login]
				HandlePowerKey=ignore
				HandlePowerKeyLongPress=poweroff
			CONF
		)
		f+~ /etc/udev/rules.d/50-power-change.rules - - - - $(
			echo ''$(
			)'ACTION=="change", SUBSYSTEM=="power_supply", '$(
			)'ENV{POWER_SUPPLY_TYPE}=="Mains", RUN+="'$(
			)"$(command -v sh) -l $(sudo -u mil sh -lc 'command -v gui')"$(
			)' -u mil localhost swaymsg seat seat0 cursor move 0 1"' \
				| base64 | tr -d '\n'
		)
	EOF
	sudo systemctl enable --now avahi-daemon
	;;
Darwin)
	#Tap-to-click
	defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
	defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad \
		Clicking -bool true
	defaults write NSGlobalDomain com.apple.mouse.scaling 0.6875
	defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
	defaults write NSGlobalDomain com.apple.trackpad.scaling -int 1
	#Style
	defaults write NSGlobalDomain AppleHighlightColor \
		"0.847059 0.847059 0.862745"
	defaults write NSGlobalDomain AppleInterfaceStyle Dark
	defaults write NSGlobalDomain AppleAquaColorVariant 6
	defaults write NSGlobalDomain _HIHideMenuBar -bool true
	defaults write com.apple.dock autohide -bool true
	defaults write com.apple.dock autohide-delay -float 1000
	defaults write com.apple.dock no-bouncing -bool true
	defaults write com.apple.dock mru-spaces -bool false
	defaults write com.apple.finder ShowPathbar -bool true
	defaults write com.apple.finder QuitMenuItem -bool true
	killall Dock Finder SystemUIServer
	defaults write com.apple.Terminal FocusFollowsMouse -string YES
	defaults write com.apple.Terminal AppleShowScrollBars -string WhenScrolling

	tmp="$(mktemp -d)"
	defaults export com.apple.Terminal - \
		| tee "$tmp/com.apple.Terminal.plist" \
		| plutil -extract "Window Settings.Basic.Font" raw - \
		| base64 -d \
		| plutil -convert xml1 - -o "$tmp/oldfont.plist" \
		&& /usr/libexec/PlistBuddy -c 'Set :$objects:1:NSSize 13' \
			"$tmp/oldfont.plist" \
		&& plutil -convert binary1 "$tmp/oldfont.plist" -o "$tmp/font.plist" \
		&& <"$tmp/com.apple.Terminal.plist" plutil \
			-replace "Window Settings.Basic.Font" \
			-data "$(base64 -i "$tmp/font.plist")" - -o - \
		| defaults import com.apple.Terminal -
	#Default software
	brew install hammerspoon pinentry-mac
	#Hammerspoon XDG
	defaults write org.hammerspoon.Hammerspoon MJConfigFile \
		"$XDG_CONFIG_HOME/hammerspoon/init.lua"
	sudo bclm persist
	;;
esac
