#!/usr/bin/env sh
# shellcheck disable=SC2016
#browser - open default browser on current platform
set -eu

die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
exists() { command -v "$1" >/dev/null 2>&1; }
sponge() { set -- "$1" "$(mktemp)" && cat >"$2" && sudo mv "$2" "$1"; }

# FIREFOX ---------------------------------------------------------------------
ff_init_profile() { #1: name
    if ! FIREFOX_PROFILE="$(
        firefox_cli -b "$BROWSER" -P "$1" get_path 2>/dev/null
    )"; then
        case "$BROWSER-$(uname -s)" in
        librewolf-Darwin)
            POLICIES="/Applications/LibreWolf.app/Contents/Resources/$(
            )distribution/policies.json"
            ;;
        librewolf-Linux)
            POLICIES="/usr/lib/librewolf/distribution/policies.json"
            ;;
        esac
        if [ -n "$POLICIES" ]; then
            <"$POLICIES" jq '
                    .policies.Extensions.Install = []
                    | .policies.ExtensionSettings = {
                        "uBlock0@raymondhill.net": {
                            "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
                            "installation_mode": "force_installed"
                        },
                        "passff@invicem.pro": {
                            "install_url": "https://addons.mozilla.org/firefox/downloads/latest/passff/latest.xpi",
                            "installation_mode": "force_installed"
                        },
                        "idcac-pub@guus.ninja": {
                            "install_url": "https://addons.mozilla.org/firefox/downloads/latest/istilldontcareaboutcookies/latest.xpi",
                            "installation_mode": "force_installed"
                        }
                    }
                ' | sponge "$POLICIES"
        fi
        "$BROWSER" -CreateProfile "$1"
        until FIREFOX_PROFILE="$(
            firefox_cli -b "$BROWSER" -P "$1" get_path
        )"; do
            sleep 1
        done
        ln -sf "$XDG_CONFIG_HOME/firefox/user.js" "$FIREFOX_PROFILE/user.js"
        mkdir -p "$FIREFOX_PROFILE/chrome"
        ln -sf "$XDG_CONFIG_HOME/firefox/chrome/userChrome.css" \
            "$FIREFOX_PROFILE/chrome/userChrome.css"
        pmmux -1 'git!https://codeberg.org/PassFF/passff-host 1.2.5 \
            make VERSION=1.2.5 BROWSER="$BROWSER" install'
        pmmux -1 apk+tree apt+tree brew+tree dnf+tree pacman+tree
    fi
}

ff_list_tabs() {
    firefox_cli -b "$BROWSER" -P "${PROFILE-standard}" extract \
        sessionstore-backups/recovery.jsonlz4 \
        | jq -r '.windows | .[].tabs | .[] | .entries[.index - 1]
            | "\(.url) \(.title)"'
}

browser_ff() {
    ff_init_profile "${PROFILE-standard}"
    case "${1-}" in
    list_tabs)
        ff_list_tabs
        return
        ;;
    http://localhost:*)
        if ff_list_tabs | grep -qF "$1"; then
            notify-send 'Server' "$1 ready"
            return
        fi
        ;;
    esac
    export PROFILE
    ([ "${XDG_SESSION_TYPE-}" != wayland ] || ! exists swaymsg || sh -c '
        sway_wait_fullscreen() {
            i=0
            until i="$((${i-0} + 1))" && [ "$i" -gt 9 ] ||
                swaymsg -t get_tree | jq -e --arg id "${PROFILE-${BROWSER}}" "
                    .nodes | .[] | recurse(.nodes[]?) |
                    select(.app_id == \$id).fullscreen_mode != 0
                " >/dev/null 2>&1; do sleep 0.1; done
        }
        i=0
        until i="$((${i-0} + 1))" && [ "$i" -gt 9 ] ||
            swaymsg -t subscribe "[ \"window\" ]" |
                jq -e ".change == \"new\"" >/dev/null 2>&1; do sleep 0.1; done
        sleep 0.1
        swaymsg "[app_id=${PROFILE-${BROWSER}}] focus"
        sleep 0.1
        sway_wait_fullscreen
        swaymsg fullscreen disable
        sway_wait_fullscreen
        swaymsg fullscreen disable
    ' &)
    exec "$BROWSER" --name="${PROFILE-${BROWSER}}" -P "${PROFILE-standard}" \
        "$@"
}

# SAFARI ----------------------------------------------------------------------
browser_safari() {
    case "${1-}" in
    list_tabs)
        osascript -e 'set output to ""
            tell application "Safari"
                repeat with t in tabs of windows
                    set output to output & URL of t & " " & name of t & "\n"
                end repeat
            end tell'
        ;;
    *) exec open -a Safari "$@" ;;
    esac
}

# MAIN ------------------------------------------------------------------------
BROWSER=librewolf
while getopts 'b:P:' OPT "$@"; do
    case "$OPT" in
    b) BROWSER="$OPTARG" ;;
    P) PROFILE="$OPTARG" ;;
    *) die "ERROR: Unknown option: %OPT" ;;
    esac
done
shift $((OPTIND - 1)) && OPTIND=1
case "$BROWSER" in
firefox | librewolf) browser_ff "$@" ;;
safari) browser_safari "$@" ;;
esac
