#!/usr/bin/env sh
set -eu

if [ "${SEEDBOX_HOST-$(uname -n)}" = "$(uname -n)" ]; then
    docker start deluge \
        || notify-send Deluge "Could not start daemon"
else
    ssh "$SEEDBOX_HOST" docker start deluge \
        && exec ssh -fNTL 58846:localhost:58846 "$SEEDBOX_HOST" \
        || notify-send Deluge "Could not connect to host."
fi
