#!/usr/bin/env sh
#editor - pick the right editor and launch it
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

get_exe() {
	if [ "$(uname -s)" = Darwin ] && exists /usr/local/bin/vis; then
		echo /usr/local/bin/vis
	elif [ "$(uname -s)" = Darwin ] && exists /opt/homebrew/bin/vise; then
		echo /opt/homebrew/bin/vise
	elif [ "$(uname -s)" != Darwin ] && exists vis; then
		command -v vis
	else
		false
	fi
}

ewrap() {
	if get_exe >/dev/null; then
		exec "$(get_exe)" "$@"
	elif exists vim; then
		exec vim "$@"
	else
		exec vi "$@"
	fi
}

editor() {
	[ ! "$TERM" = vt100 ] || exec vi "$@"
	if ! get_exe >/dev/null; then
		pmmux -1 apk+vis apt+vis brew+vis dnf+vis pacman+vis 2>/dev/null || :
	fi
	ewrap "$@"
}

editor "$@"
