#!/usr/bin/env sh
#editor - pick the right editor and launch it
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

ewrap1() {
    if [ "$(uname -s)" = Darwin ] && exists vise; then
        ! </proc/$PPID/cmdline grep -q alot || exec 2<&1
        exec vise "$@"
    elif exists vis; then
        ! </proc/$PPID/cmdline grep -q alot || exec 2<&1
        exec vis "$@"
    elif exists vim; then
        exec vim "$@"
    else
        exec vi "$@"
    fi
}

ewrap0() {
    encoding="$(cat "$1" 2>/dev/null | txtconv -p)"
    if [ -f "$1" ] && [ -n "$encoding" ]; then
        txtconv -i "$1"
        (ewrap1 "$@")
        txtconv -i"$encoding" "$1"
    else
        ewrap1 "$@"
    fi
}

editor() {
    if ! exists vise && [ "$(uname -s)" = Darwin ] || ! exists vis; then
        pmmux -1 \
            apk+vis \
            apt+vis \
            brew+vis \
            dnf+vis \
            pacman!'
                sudo pacman --needed --noconfirm --asdeps -qS \
                    libtermkey tre unibilium lua lua-lpeg
                pmmux -1 git!"https://git.sr.ht/~mcepl/vis master \
                    ./configure
                    make
                    sudo make install
                "
            '
        [ -d "$XDG_CONFIG_HOME/vis/vis-cursors" ] \
            || git clone https://github.com/erf/vis-cursors.git \
                "$XDG_CONFIG_HOME/vis/vis-cursors"
        [ -d "$XDG_CONFIG_HOME/vis/vis-lspc" ] \
            || git clone https://milhnl@github.com/milhnl/vis-lspc \
                "$XDG_CONFIG_HOME/vis/vis-lspc"
    fi
    if (test -e "$1" && ! test -w "$1") || \
            ( ! test -e "$1" && ! test -w "$(dirname "$1")"); then
        exec sudo sh -c "
            export XDG_CONFIG_HOME='$XDG_CONFIG_HOME'
            export VIS_PATH='$XDG_CONFIG_HOME/vis'
            export PATH='\$PATH:$PATH'
            exec '$(sh -c 'command -v editor')' \"$@\"
        " -- "$@"
    else
        printf "\e]0;edit %s\a" "$1"
        ewrap0 "$@"
    fi
}

editor "$@"
