#!/usr/bin/env sh
set -eu

quote() {
    for x do
        printf %s\\n "$x" \
            | sed "s/[[|&;<>()\\\$\`\\\\\"' $(printf '\t')*?#~=%]/\\\\&/g;
                s/\$/ \\\\/"
    done
    echo " "
}

while getopts "u:" OPT "$@"; do
    case "$OPT" in
    u) REMOTE_USER="$OPTARG";;
    esac
done

shift "$(( $OPTIND - 1 ))"
HOST="${1:-$REMOTE_HOST}"
shift
CMD="$(quote "$@" | sed "s/'/'\\\\''/g")"

ssh -t "$HOST" "
    set -x
    switch_user() {
        if [ -n \"${REMOTE_USER:-}\" ]; then
            exec sudo -u \"${REMOTE_USER:-}\" sh -lic \"\$@\"
        elif id -u unattended >/dev/null 2>&1; then
            exec sudo -u unattended sh -lic \"\$@\"
        else
            exec sh -lic \"\$@\"
        fi;
    }
    switch_user '
    set -a
    XDG_RUNTIME_DIR=\"/run/user/\$(id -u)\"
    SWAYSOCK=\"\$XDG_RUNTIME_DIR/sway-ipc.\$(id -u).\$(\\
        pgrep -u \"\$(whoami)\" \"^sway\\\$\").sock\"
    WAYLAND_DISPLAY=\"\$SWAYSOCK.display\"
    mkfifo \"\$WAYLAND_DISPLAY\"
    swaymsg exec \"echo \\\"\\\$WAYLAND_DISPLAY\\\">\\\"\$WAYLAND_DISPLAY\\\"\"
    WAYLAND_DISPLAY=\"\$(cat \"\$WAYLAND_DISPLAY\"; rm \"\$WAYLAND_DISPLAY\")\"
    MOZ_ENABLE_WAYLAND=1
    exec $CMD
'"