#!/usr/bin/env sh
#htpasswd - set htpasswd
set -eu

owner_of() { ls -l "$1" | awk -v OFS=: '{ print $3, $4 }'; }

htpasswd() { #htpasswd_file user
    if [ $# -ne 2 ]; then
        echo "USAGE: $0 <htpasswd_file> <user>" >&2
        exit 1
    fi
    set -- "$1" "$2" "$(owner_of "$1")"
    {
        cat "$1" 2>/dev/null | sed "/^$2:/d" ||:
        printf "$2:"
        openssl passwd -apr1
    } >"$1.new"
    mv "$1.new" "$1"
    [ "$(owner_of "$1")" = "$3" ] || chown "$3" "$1"
    chmod og-rwx "$1"

    case "${3%:*}" in
    http) systemctl reload nginx || systemctl restart nginx;;
    esac
}

htpasswd "$@"
