#!/usr/bin/env sh
#htpasswd - set htpasswd
set -eu

htpasswd() { #htpasswd_file user
    {
        sudo -u http cat "$1" 2>/dev/null | sed "/^$2:/d" ||:
        printf "$2:"
        openssl passwd -apr1
    } >"$1.new"
    sudo mv "$1.new" "$1"
    sudo chown http:http "$1"
    sudo chmod og-rwx "$1"

    sudo systemctl reload nginx || sudo systemctl restart nginx
}

htpasswd "$@"
