#!/usr/bin/env sh
set -eu

export IFNAME="$(\
    find /sys/class/net -follow -maxdepth 2 -name phy80211 2>/dev/null \
        | head \
        | cut -d / -f 5)"
WIFI_FOLDER="wifi"

for file in "$PASSWORD_STORE_DIR/$WIFI_FOLDER/"*; do
    [ -e "$file" ] || continue
    ssid="${file#$PASSWORD_STORE_DIR/$WIFI_FOLDER/}"
    ssid="${ssid%.gpg}"
    gpg -qd "$file" | {
        if :; then #Check other network daemon
            awk '
                function escape(str) {
                    gsub("[^-A-Za-z0-9_.,,]", "\\\\&", str)
                    return str
                }
                function mad_escape(str) {
                    if (match(str, "^\"") == 1) {
                        return "\\\"\\\"" escape(str) "\\\""
                    } else {
                        return escape(str)
                    }
                }
                BEGIN {
                    o["security"] = "wpa"
                    o["connection"] = "wireless"
                    o["ip"] = "dhcp"
                    o["description"] = "Profile for " ENVIRON["IFNAME"]
                }
                NR == 1 {
                    o["key"] = $0
                }
                NR != 1 {
                    sub(": ?", ":")
                    o[substr($0, 0, index($0, ":") - 1)] = \
                        substr($0, index($0, ":") + 1)
                }
                END {
                    printf("Description=%s\n", escape(o["description"]))
                    printf("ESSID=%s\n", mad_escape(o["essid"]))
                    printf("Key=%s\n", mad_escape(o["key"]))
                    printf("Connection=%s\n", escape(o["connection"]))
                    printf("Interface=%s\n", escape(ENVIRON["IFNAME"]))
                    printf("Security=%s\n", escape(o["security"]))
                    printf("IP=%s\n", escape(o["ip"]))
                }
            ' \
            | sudo tee "/etc/netctl/$IFNAME-$ssid" >/dev/null
        fi
    }
done

if :; then #Check other network daemon
    systemctl is-active --quiet netctl-auto@"$IFNAME" \
        || sudo ip link set "$IFNAME" down
    sudo systemctl enable --now netctl-auto@"$IFNAME".service
fi
