#!/usr/bin/env sh
#m - do all the things with mail

LOCKDIR="$XDG_RUNTIME_DIR/mdaemon"
lock() { mkdir "$LOCKDIR"; }
unlock() { rm -r "$LOCKDIR"; }
sponge() { set -- "$1" "$(mktemp)"; cat >"$2"; mv "$2" "$1"; }
exists() { command -v "$1" >/dev/null 2>&1; }

make_ish() { #1: old, 2: new, 3... cmd
    if [ -z "$(find -L "$2" -newer "$1" -exec echo 1 \; 2>/dev/null)" ]; then
        <"$1" sh -c 'shift 2; exec "$@"' -- "$@" | sponge "$2"
    fi
}

m_send() {
    {
        if exists pandoc; then
            maildown pandoc
        elif exists markdown; then
            maildown markdown
        else
            cat
        fi
    } | msmtp \
        "$([ "$(uname -s)" = Darwin ] && echo '--tls-trust-file=system')" \
        "$@"
}

m_sync() {
    [ "$#" -eq 0 ] && set -- -a
    mkdir -p "$PREFIX/var/mail/gmail"
    mkdir -p "$PREFIX/var/mail/eforah"

    MBSYNCRC="$XDG_CONFIG_HOME/isync/mbsyncrc"
    if [ "$(lsb_release -sir 2>/dev/null)" = "Ubuntu 16.04" ]; then
        make_ish "$MBSYNCRC" "$MBSYNCRC-16.04" sed 's/^SSLType.*/UseIMAPS yes/'
        MBSYNCRC="$MBSYNCRC-16.04"
    elif [ "$(uname -s)" = "Darwin" ]; then
        make_ish "$MBSYNCRC" "$MBSYNCRC-Darwin" sed \
            -e 's|CertificateFile.*|CertificateFile "/etc/ssl/cert.pem"|' \
            -e 's|~/.local|'"$PREFIX"'|'
        MBSYNCRC="$MBSYNCRC-Darwin"
    fi

    mbsync -c "$MBSYNCRC" "$@"
    notmuch new
}

m_daemon() {
    if ! lock; then echo "Another instance seems to be running" >&2; exit 1; fi
    trap unlock EXIT
    touch "$LOCKDIR/notified"
    while true; do
        m_sync "$@"
        notmuch show --format=json tag:unread AND NOT tag:killed \
            | jq -r '. [] | .[] | .[]
                | select(type == "object")
                | [(.timestamp | todateiso8601), .id, .headers.Subject]
                | @tsv' \
            | cat /dev/stdin "$LOCKDIR/notified" \
            | sort -u \
            | tee "$LOCKDIR/notified.new" \
            | comm -23 - "$LOCKDIR/notified" \
            | while read -r eh eh2 subject; do
                notify-send -u low "﫯  $subject"
            done
        mv "$LOCKDIR/notified.new" "$LOCKDIR/notified"

        if (grep -q Discharging /sys/class/power_supply/*/status); then
            sleep 3600
        else
            sleep 60
        fi
    done
}

m_view() {
    printf "\e]0;mail\a"
    tput smcup
    alot -p "$MAILDIR" "$@"
    tput rmcup
}

(pgrep -f 'mail_client daemon' || mail_client daemon&) >/dev/null 2>&1
if [ "$#" -eq 0 ]; then set -- view; fi
case "$1" in
send) shift; m_send "$@";;
sync) shift; m_sync "$@";;
daemon) shift; m_daemon "$@";;
view) shift; m_view "$@";;
*) notmuch "$@";;
esac
