#!/usr/bin/env python3
#maildown - converts markdown mail to multipart
import sys
import subprocess
import email.parser
from email import policy

mail = email.parser.Parser(policy=policy.SMTP).parse(sys.stdin)
body = mail.get_body('plain')
(markdown, error) = subprocess.Popen(
    sys.argv[1:],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE
).communicate(input=body.get_payload(decode=True))
body.add_alternative(markdown.decode('utf-8'), subtype='html')
print(mail.as_string())
