#!/usr/bin/env sh
set -eu

die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }

show() {
    printf "\033[0;31m%s \033[0;32m%s\033[0m\n" "$1" "$2"
}

sed='sed'
mv='mv'
while getopts 'nEe:d:x:' OPT "$@"; do
    [ -z "${OPTARG:-}" ] || OPTARG="$(echo "$OPTARG" | sed "s/'/'\\\\''/")" #'
    case "$OPT" in
    n) mv=show ;;
    e) cmd="${cmd+$cmd | }$sed '$OPTARG'" ;;
    d) cmd="${cmd+$cmd | } { printf %s '${OPTARG%/}/'; sed 's_.*/__'; }" ;;
    x) cmd="${cmd+$cmd | } sh -c '$OPTARG'" ;;
    E) sed='sed -E' ;;
    *) die "ERROR: Unknown option: %OPT" ;;
    esac
done
shift $((OPTIND - 1)) && OPTIND=1
for x; do
    y="$(echo "$x" | eval "$cmd")" || exit 1
    if [ "$x" != "$y" ]; then
        "$mv" "$x" "$y" || exit 1
    fi
done
