#!/usr/bin/env sh
#rgex - replace string in all files in wd
set -eu

rgex() { #1: selector, 2: replacement
    [ $# -eq 2 ] || {
        printf "usage: rgex SELECTOR REPLACEMENT\n"
        return 1
    }
    rg -l "$1" | xargs -rn1 ex -sc "%s/$1/$2/|wq!"
}
rgex "$@"
