#!/usr/bin/env sh
#rpi_img - make arch arm disk image for raspberry pi
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
die() { printf '%s\n' "$*" >&2; exit 1; }
device_of() { df -P "$1" | awk 'END { print $1 }'; }

clean() {
    sync
    sudo umount "$(device_of "$ROOT/boot")" "$(device_of "$ROOT")"
    sudo rmdir "$ROOT" 2>/dev/null
    ! losetup --list | grep -q "$DEVICE" || sudo losetup -d "$DEVICE"
}

get_image() { #1: version
    case "$1" in
    1) set -- rpi;;
    2) set -- rpi-armv7;;
    3) set -- rpi-aarch64;;
    4) set -- rpi-aarch64;;
    esac
    set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
    set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
    mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img"
    if exists curl; then
        test -e "$2" && curl -Lo "$2" -z "$2" "$1" || true
        test ! -e "$2" && curl -Lo "$2" "$1" || true
    elif exists wget; then
        wget -N "$1"
    fi
    echo "$2"
}

create_root() {
    echo 'o; n;p;1;;+200M; t;c; n;p;2;;; w;q;' \
        | tr -d \  | tr ';' '\n' \
        | sudo fdisk "$1" || true #rereading partition table may have failed
    sync
    sudo blockdev --rereadpt -v "$1" || sudo partprobe "$1"
    (
        set -- $(lsblk -lnoNAME "$1" | sort | sed '1d;s|^|/dev/|')
        yes | sudo mkfs.ext4 $2 && sudo mount $2 "$ROOT"
        cd "$ROOT"
        yes | sudo mkfs.vfat $1 && sudo mkdir -p boot && sudo mount $1 boot
    )
}

rpi_img() { #1: path, 2: version, 3: size
    ROOT="$(mktemp -d)"
    DEVICE="$1"
    trap clean EXIT
    exists mkfs.vfat || die "error: install mkfs.vfat"
    exists mkfs.ext4 || die "error: install mkfs.ext4"
    if [ $# -eq 3 ] && [ ! -b "$1" ]; then
        sudo modprobe loop
        truncate -s "$3" "$1"
        set -- "$(sudo losetup -fP --show "$1")" "$2" "$3"
        expr "$1" : /dev/ || die "error: loopback setup failed"
    elif [ $# -ne 2 ]; then
        die "usage: rpi_img DEVPATH VERSION [SIZE (only if loop device)]"
    fi
    create_root "$1"
    [ -d "$ROOT" ] && [ -d "$ROOT/boot" ] || die "error: fs setup/mount failed"
    echo "Actually downloading/writing data. This may take a long time..." >&2
    sudo bsdtar -xpf "$(get_image "$2")" -C "$ROOT"
    clean
    trap - EXIT
}

rpi_img "$@"
