#!/usr/bin/env sh
set -eu

daemon() (exec "$@" >/dev/null 2>&1 &)
pgrep() { ps -Aocomm | grep -qxF "$1"; }

service_shairport_sync() {
    case "$1" in
    start)
        sudo systemctl start avahi-daemon
        pgrep nqptp || {
            daemon sudo nqptp
            sleep 1
        }
        pgrep shairport-sync || {
            if ps -u"$USER" -Aocomm= | grep -qxE "pipewire|pulseaudio"; then
                daemon shairport-sync -o pa
            else
                daemon shairport-sync
            fi
        }
        ;;
    stop)
        pkill shairport-sync || :
        sudo pkill nqptp || :
        ;;
    is-active)
        ps -u "$USER" -Aocomm= | grep -qxE "shairport-sync"
        ;;
    esac
}
service_shairport_sync "$@"
