#!/usr/bin/env sh
awk '
    BEGIN { srand() }
    {
        l = length($0)
        for (i=1; i<=l; i++) printf("%s", rand() < 0.5 \
            ? toupper(substr($0, i, 1)) \
            : tolower(substr($0, i, 1)))
        print ""
    }
'
