#!/usr/bin/env sh
#swaystatus - sway bar status line
set -eu

battery() (
    cd "$1"
    echo "scale=1;$(cat charge_now)*100/$(cat charge_full)" | bc
)

echo '{ "version": 1 }'

echo '['
while true; do
    DATE="$(date '+%Y-%m-%d')"
    TIME="$(date '+%R')"
    echo '[
      {
        "markup": "pango",
        "full_text": "'"$(battery /sys/class/power_supply/BAT*)"'%"
      },
      {
        "markup": "pango",
        "full_text": "<span weight=\"light\">'"$DATE"'</span> '"$TIME"'"
      },
    ],'
    sleep 60;
done
echo ']' #eh
