#!/usr/bin/env sh
#swaystatus - sway bar status line
set -eu

battery() (
    cd "$1"
    if [ -e charge_now ]; then
        echo "scale=1;$(cat charge_now)*100/$(cat charge_full)" | bc
    else
        echo "scale=1;$(cat energy_now)*100/$(cat energy_full)" | bc
    fi
)

echo '{ "version": 1 }'

echo '['
while true; do
    DATE="$(date '+%Y-%m-%d')"
    TIME="$(date '+%R')"
    echo '[
      {
        "markup": "pango",
        "full_text": "'"$(ump current)"'"
      },
      {
        "markup": "pango",
        "full_text": "'"$(battery /sys/class/power_supply/BAT*)"'%"
      },
      {
        "markup": "pango",
        "full_text": "'"$DATE"' <span weight=\"bold\">'"$TIME"'</span>"
      },
    ],'
    sleep 60;
done
echo ']' #eh
