#!/usr/bin/env sh
#swaystatus - sway bar status line
set -eu

battery_charge() (
    cd "$1"
    if [ -e charge_now ]; then
        echo "scale=1;$(cat charge_now)*100/$(cat charge_full)" | bc
    else
        echo "scale=1;$(cat energy_now)*100/$(cat energy_full)" | bc
    fi
)

np() {
    NP="$(ump current)"
    [ "$NP" != null ] || return
    echo '
      {
        "markup": "pango",
        "full_text": "'"$(ump current)"'",
        "separator": false,
        "separator_block_width": 50
      },'
}

battery() {
    CHARGE="$(battery_charge /sys/class/power_supply/BAT*)" || return
    case "$(cat /sys/class/power_supply/BAT0/status)" in
    Charging) ICON=""; STATE="<span>";;
    Unknown) ICON=""; STATE="<span foreground=\\\"#ffffffaa\\\">";;
    Discharging)
        if [ ${CHARGE%.*} -lt 20 ]; then ICON="";
        elif [ ${CHARGE%.*} -lt 40 ]; then ICON="";
        elif [ ${CHARGE%.*} -lt 60 ]; then ICON="";
        elif [ ${CHARGE%.*} -lt 80 ]; then ICON="";
        else ICON=""; fi
        STATE="<span>"
        ;;
    esac
    echo '
      {
        "markup": "pango",
        '"$( [ ${CHARGE%.*} -lt 15 ] && echo '"urgent": true,')"'
        "full_text": " '"$ICON  $STATE$CHARGE" '</span>",
        "separator": false,
        "separator_block_width": 50
      },'
}

echo '{ "version": 1 }'

echo '['
while true; do
    DATE="$(date '+%Y-%m-%d')"
    TIME="$(date '+%R')"
    echo '[
      '"$(np)"'
      '"$(battery)"'
      {
        "markup": "pango",
        "full_text": "'"$DATE"'  <span weight=\"bold\">'"$TIME"'</span>",
        "separator": false,
        "separator_block_width": 30
      },
    ],'
    sleep 60;
done
echo ']' #eh
