#!/usr/bin/env bash
#tagalbum - interactively edit tags for flac files
set -eu

die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac }

gettags() { #@: files to get tags from
    for x; do
        case "$x" in
        *.flac) metaflac --export-tags-to=- "$x" | sed 's/[^=]*/\U&/' ;;
        *.mp3)
            mid3v2 -l "$x" | awk -vFS== '
                /^[0-9A-Z][0-9A-Z][0-9A-Z][0-9A-Z]=/ {
                    tags[$1] = $2
                }
                END {
                    map["TPE1"] = "ALBUMARTIST"
                    map["TPE2"] = "ARTIST"
                    map["TALB"] = "ALBUM"
                    map["TYER"] = "DATE"
                    map["TDRC"] = "DATE"
                    map["TCON"] = "GENRE"
                    map["TRCK"] = "TRACKNUMBER"
                    map["TPOS"] = "DISCNUMBER"
                    map["TIT2"] = "TITLE"
                    for (key in tags)
                        if (key in map)
                            printf("%s=%s\n", map[key], tags[key])
                    if (! ("TPE2" in tags))
                        printf("ARTIST=%s\n", tags["TPE1"])
                }
            '
            ;;
        esac
    done
}

settags() { #1: audiofile
    case "$1" in
    *.flac) metaflac --remove-all-tags --import-tags-from=- "$i" ;;
    *.mp3)
        sed "/[A-Z][A-Z0-9]\{3\}=/!d;s/'/'\\\\''/g;s/=/='/;s/\$/'/" \
            | {
                eval "$(cat)"
                mid3v2 --TPE1 "$ALBUMARTIST" --TPE2 "$ARTIST" -A "$ALBUM" \
                    -t "$TITLE" -g "$GENRE" -y "$DATE" \
                    --TPOS "${DISCNUMBER-}" -T "${TRACKNUMBER#/*}" "$1"
            }
        ;;
    esac
}

getshared() {
    gettags "$@" | awk -F= '
        BEGIN {
            m["ARTIST"] = ""
            m["ALBUM"] = ""
            m["DATE"] = ""
            m["ALBUMARTIST"] = ""
            m["GENRE"] = ""
        }
        {
            if ($1 in m) {
                v = substr($0, length($1) + 2);
                if ($1 in m && m[$1] == "") {
                    m[$1] = v;
                } else if (m[$1] != v) {
                    delete m[$1];
                }
            }
        }
        END {
            if ("ARTIST" in m && m["ARTIST"] != "")
                printf("%s=%s\n", "ARTIST", m["ARTIST"])
            if ("ALBUM" in m && m["ALBUM"] != "")
                printf("%s=%s\n", "ALBUM", m["ALBUM"])
            if ("DATE" in m && m["DATE"] != "")
                printf("%s=%s\n", "DATE", m["DATE"])
            if ("ALBUMARTIST" in m && m["ALBUMARTIST"] != "")
                printf("%s=%s\n", "ALBUMARTIST", m["ALBUMARTIST"])
            if ("GENRE" in m && m["GENRE"] != "")
                printf("%s=%s\n", "GENRE", m["GENRE"])
        }
    '
}

getpersong() {
    gettags "$@" \
        | sed -E 's/(TRACKNUMBER=[0-9]*)[^0-9].*/\1/' \
        | sed -n '/^\(TITLE\|TRACKNUMBER\|ARTIST\)=/p'
}

gettag() { #1: tagfile, 2: propertyname
    sed -n 's/^'"$2"'=\(.*\)/\1/p' <"$1"
}

settag() { #1: tagfile, 2: propertyname, 3: value
    sed -i '/^'"$2"'=/d' "$1"
    [ -z "${3:-}" ] || echo "$2=$3" >>"$1"
}

editorfor() { #1: tagfile, 2: propertyname
    oldval="$(gettag "$1" "$2" | titlecase)"
    read -e -i "$oldval" -p "$(echo "$2" | sed 's/[^ ]\+/\L\u&/g'): " newval
    settag "$1" "$2" "$newval"
}

unset DISCNUMBER
while getopts n: OPT "$@"; do
    case "$OPT" in
    n) export DISCNUMBER="$OPTARG" ;;
    *) printf "ERROR: Unknown option: %s\n" "$OPT" >&2 && return 1 ;;
    esac
done
shift $((OPTIND - 1)) && OPTIND=1

[ "$#" -ne 0 ] || set -- .
if [ "$#" -eq 1 ] && [ -d "$1" ]; then
    if ! fnmatch '*/\*.flac' "$1"/*.flac; then
        set -- "$1"/*.flac
    elif ! fnmatch '*/\*.mp3' "$1"/*.mp3; then
        set -- "$1"/*.mp3
    else
        die "ERROR: No flac or mp3 files found"
    fi
fi

wd="$(mktemp -d)"

#Get the shared tags
getshared "$@" >"$wd/shared"
[ -z "${DISCNUMBER-}" ] || settag "$wd/shared" DISCNUMBER "$DISCNUMBER"

editorfor "$wd/shared" ARTIST
if [ -n "$(gettag "$wd/shared" ARTIST)" ]; then
    settag "$wd/shared" ALBUMARTIST "$(gettag "$wd/shared" ARTIST)"
else
    editorfor "$wd/shared" ALBUMARTIST
fi
editorfor "$wd/shared" ALBUM
editorfor "$wd/shared" DATE
editorfor "$wd/shared" GENRE

for i in "$@"; do
    getpersong "$i" >"$wd/current"

    editorfor "$wd/current" TITLE
    [ -z "$(gettag "$wd/shared" ARTIST)" ] \
        && editorfor "$wd/current" ARTIST \
        || settag "$wd/current" ARTIST

    cat "$wd/shared" "$wd/current" | sort | uniq | settags "$i"
done
