#!/usr/bin/env sh
#VBoxManage - fix clipboard issue
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }

save() {
    for x; do
        printf %s\\n "$x" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"
    done
    echo " "
}

eval "set -- $(save "$@" | sed "s/'--clipboard'/'--clipboard-mode'/")"

PATH="$(echo "$PATH" | sed "s|$HOME[^:]*:||")" VBoxManage "$@"
