#!/usr/bin/env sh
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
vc_copy() { printf "%s" "System clipboard not supported" >&2 && exit 1; }
vc_paste() { printf "%s" "System clipboard not supported" >&2 && exit 1; }
vc_usable() { return 0; }

get_tty() {
	set -- /dev/fd/1
	! [ -t "${1#/dev/fd/}" ] || { printf "%s" "$1" && return; }
	set -- "$(ps -o pid=,tty= | awk -vpid=$$ '$1 == pid { print $2 }')"
	set -- "${1% }"
	case "$1" in
	*,*)
		set -- "$(printf "%x,%x" "${1%,*}" "${1#*,}")"
		for x in /dev/pts/* /dev/tty*; do
			if [ "$(stat -c "%t,%T" "$x")" = "$1" ]; then
				printf "%s" "$x"
				return
			fi
		done
		;;
	*) printf "/dev/%s" "$1" ;;
	esac
}

#This only works in my config, as I forward TERM_PROGRAM with ssh
if [ "${TERM_PROGRAM-}" != Apple_Terminal ] && tput Ms >/dev/null 2>&1; then
	vc_copy() {
		printf '\033]52;c;%s\a' "$(base64)" >"$(get_tty)"
	}
	vc_paste() (
		tty="$(get_tty)"
		stty_reset="$(stty -g <"$tty")"
		trap "stty '$stty_reset' <\"\$tty\"" EXIT \
			&& stty -icanon min 1 time 0 -echo <"$tty"
		printf '\033]52;c;?\a' >"$tty"
		case "$TERM" in
		xterm-ghostty | xterm-kitty)
			<"$tty" awk '
				BEGIN { RS="\033"; FS=";" }
				NR == 2 { print $3; exit }
			' | base64 -d
			;;
		alacritty)
			<"$tty" awk '
				BEGIN { RS="\a"; FS=";" }
				{ print $3; exit }
			' | base64 -d
			;;
		*)
			#Will just hang on WezTerm
			dd bs=1 count=7 2>/dev/null <"$tty" >/dev/null
			response=''
			while :; do
				c=$(dd bs=1 count=1 2>/dev/null <"$tty")
				[ "$c" != "$(printf '\a')" ] || break
				[ "$c" != "$(printf '\033')" ] || {
					dd bs=1 count=1 >/dev/null 2>&1 <"$tty"
					break
				}
				response="$response$c"
			done
			printf %s "$response" | base64 -d
			;;
		esac
		stty "$stty_reset" <"$tty"
	)
elif [ -n "${WAYLAND_DISPLAY-}" ] && exists wl-copy; then
	vc_copy() { exec 2>/dev/null && wl-copy; }
	vc_paste() { wl-paste --no-newline -t text; }
elif [ -n "${DISPLAY-}" ] && exists xsel; then
	vc_copy() { xsel -bi; }
	vc_paste() { xsel -bo; }
elif [ -n "${DISPLAY-}" ] && exists xclip; then
	vc_copy() { xclip -selection clipboard -i >/dev/null 2>&1; }
	vc_paste() { xclip -selection clipboard -o; }
elif exists pbcopy; then
	vc_copy() { pbcopy; }
	vc_paste() { pbpaste; }
elif [ -c /dev/clipboard ]; then
	vc_copy() { cat >/dev/clipboard; }
	vc_paste() { cat /dev/clipboard; }
elif grep -iq microsoft /proc/version 2>/dev/null && exists clip.exe; then
	vc_copy() { clip.exe; }
	vc_paste() { powershell.exe -c Get-Clipboard | sed "s/$(printf \\r)\$//"; }
else
	vc_usable() { return 1; }
fi

case "$1" in
--usable) vc_usable ;;
--copy) vc_copy ;;
--paste) vc_paste ;;
*)
	printf "%s" "$(basename $0) [--usable|--copy|--paste]" >&2
	exit 1
	;;
esac
