#!/usr/bin/env sh
set -eu

wifi_qr() {
    qrencode -o - "WIFI:T:WPA;S:$1;P:$2;;" | {
        if [ -t 1 ]; then
            xdg-open "$(printf 'data:image/png;base64,'; base64)"
        else
            cat
        fi
    }
}

wifi_qr "$@"
