#!/usr/bin/env sh
#shellcheck disable=SC2016
#write_os - write os to device/file
set -eu

escape() { echo "$1" | sed "s/'/'\\\\''/g"; }
exists() { command -v "$1" >/dev/null 2>&1; }
die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
device_of() { df -P "$1" | awk 'END { print $1 }'; }
fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac }
in_dir() (cd "$1" && shift && "$@")
to_argv() (
	set +x
	while read -r LINE; do set -- "$@" "$LINE"; done
	"$@"
)
quote() {
	for x; do
		printf "'" && printf %s "$x" | sed "s/'/'\\\\''/g" && printf "' " \
			|| return 1
	done
}
sponge() { set -- "$1" "$(mktemp)" && cat >"$2" && sudo mv "$2" "$1"; }

clean() {
	sync
	(
		set -- boot ''
		while [ $# -ne 0 ]; do
			set -- "$(get_dev_for "$ROOT${1:+/$1}")" "$@"
			! [ -e "$ROOT${2:+/$2}" ] || [ -z "$1" ] \
				|| sudo umount "$1"
			shift 2
		done
	)
	if losetup --help 2>&1 | grep -q -e '--output'; then
		losetup -nONAME -j "$FILE"
	else
		{ losetup -a 2>/dev/null || :; } \
			| awk -vpath="$FILE" '
				{
					if (index($0, path))
						print substr($0, 1, index($0, ":") - 1)
				}
			'
	fi | xargs -rn 1 sudo losetup -d
	sudo rm -r "$ROOT"
}

download() { #1: url, 2: path
	mkdir -p "$(dirname "$2")"
	if exists curl; then
		if [ -e "$2" ]; then
			curl -fLo "$2" -z "$2" "$1"
		else
			curl -fLo "$2" "$1"
		fi
	elif exists wget; then
		wget "$1" -O "$2"
	fi
}

uname_to_arch() {
	case "$(uname -m)" in
	x86_64) echo x86_64 ;;
	aarch64 | arm64) echo aarch64 ;;
	armv7l) echo armv7 ;;
	armv6l) echo armhf ;;
	i?86) echo x86 ;;
	esac
}

distro_id() {
	cat /etc/os-release 2>/dev/null | sed -En 's/^ID="?(.*)"?$/\1/p'
}

get_rpi_image() { #1: version
	set -- "$(echo "$ARCH" | sed 's/armv6//')"
	set -- "rpi${1:+-$1}"
	set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
	set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
	download "$@"
	echo "$2"
}

get_dev_for() { #1: path
	mount | sed -n 's|\(/dev/[^ ]*\) on '"$1"' .*|\1|p'
}

crude_wipefs() { #1: dev
	set -- "$1" "$(blockdev --getsz "$1")"
	dd if=/dev/zero of="$1" bs=512 count=2048
	dd if=/dev/zero of="$1" bs=512 seek=$(($1 - 2048)) count=2048
}

create_root() { #1: device 2: root 3: disklabel 4?: size
	if exists apk; then
		apk add e2fsprogs sfdisk
	elif exists pacman; then
		sudo pacman --needed --noconfirm -qS e2fsprogs dosfstools
	fi
	mkfs.vfat --help >/dev/null 2>&1 || die "error: install mkfs.vfat"
	mkfs.ext4 2>&1 | grep -q Usage || die "error: install mkfs.ext4"

	if [ ! -b "$1" ]; then
		BACKING_FILE="$1"
		sudo modprobe loop
		sudo truncate -s "$4" "$1"
		if losetup --help 2>&1 | grep -q -e '--show'; then
			set -- "$(sudo losetup -fP --show "$1")" "$2" "$3" "${4:-}"
		else
			set -- "$(
				file="$(sudo losetup -f)"
				losetup -P "$file" "$1"
				echo "$file"
			)" "$2" "$3" "${4:-}"
		fi
		expr "$1" : /dev/ >/dev/null || die "error: loopback setup failed"
		FILE="$1"
		sudo chown "$(whoami)" "$BACKING_FILE"
	fi
	if exists sfdisk; then
		printf 'label: '"$3"'\n,1G,'"$(
			[ "$3" = gpt ] && echo U || echo 0c
		)"',*\n,4G,S,-\n,+,L' \
			| sudo sfdisk "$1" --wipe always --wipe-partitions always
	else
		sudo wipefs -a "$1" || crude_wipefs "$1"
		case "$3" in
		dos)
			exists fdisk || die "error: install sfdisk or fdisk"
			#echo 'o; n;p;1;;+1G; t;c; n;p;2;;+8G; t;2;82;  n;p;3;;; w;q;' \
			echo 'o; n;p;1;;+1G; t;c; n;p;2;;; w;q;' \
				| tr -d \  | tr ';' '\n' \
				| sudo fdisk "$1" || true #Maybe rereading part table failed
			;;
		gpt)
			exists fdisk || die "error: install sfdisk or sgdisk"
			sudo sgdisk -zo "$1"
			sudo sgdisk -n 1:0:1G -t 1:ef00 -A 2:set:2 "$1"
			if [ "$HARDWARE" = xps13 ]; then
				sudo sgdisk -n 2:+0:16G -t 3:8200 "$1"
				sudo sgdisk -N 3 -t 3:8304 "$1"
			else
				sudo sgdisk -N 2 -t 2:8304 "$1"
			fi
			;;
		esac
	fi
	sync
	sudo blockdev --rereadpt "$1" || sudo partprobe "$1" || :
	! exists mdev || mdev -s
	(
		set -- "$1" "$2" $(
			if exists lsblk; then
				lsblk -lnoPATH "$1" | sed 1d
			elif exists sfdisk; then
				sfdisk -l "$1" -qoDevice
			elif exists fdisk; then
				fdisk -l "$1"
			fi | sed -En 's:^(/dev[^ ]*).*:\1:p' | sort
		)
		yes | sudo mkfs.ext4 "${5:-$4}"
		sudo mount -t ext4 "${5:-$4}" "$2"
		sudo mkdir -p "$2/boot"
		yes | sudo mkfs.vfat -F 32 $3
		sudo mount -t vfat $3 "$2/boot"
		[ -z "${5:-}" ] || { sudo mkswap -L hibernate "$4"; }
	)
	[ -d "$2" ] && [ -d "$2/boot" ] || die "error: fs setup/mount failed"
}

ALPINE_REMOTE=https://dl-cdn.alpinelinux.org/alpine
[ "$(id -u)" = 0 ] \
	&& ALPINE_LOCAL="/usr/local/share/alpine-repo" \
	|| ALPINE_LOCAL="$XDG_CACHE_HOME/alpine-repo"

alpine_version_to_branch() { #1?: version
	[ $# -eq 1 ] || set -- "$(cat /etc/alpine-release)"
	case "$1" in
	*.*.*) set -- "${1%.*}" && echo "v${1#v}" ;;
	*) echo edge ;;
	esac
}

repo_location() { #1: root 2: repo 3: file
	printf "%s/%s/%s/%s%s" "$1" "$ALPINE_BRANCH" "$2" "$ARCH" "${3+/$3}"
}

apk_dl() { #1: repo 2: file
	mkdir -p "$(dirname "$(repo_location "$ALPINE_LOCAL" "$@")")"
	download \
		"$(repo_location "$ALPINE_REMOTE" "$@")" \
		"$(repo_location "$ALPINE_LOCAL" "$@")" \
		|| return 1
	repo_location "$ALPINE_LOCAL" "$@"
}

#apk_dl_pkg() { #1: repo 2: name
#    set -- "$1" "$2" "$(apk_dl "$1" APKINDEX.tar.gz)"
#    set -- "$1" "$2" "$3" "$(tar -xOf "$3" | awk '
#        /^P:'"$2"'$/ { found=1 }
#        found && /^V:/ { print substr($0,3); exit }
#    ')"
#    apk_dl "$1" "$2-$4.apk"
#}

cp_dot() { #1: new_home 2: destdir
	sudo mkdir -p "${2-}$1/.local/dot"
	DOTFILES="$(
		if [ -e "${DOTFILES-}" ]; then
			echo "$DOTFILES"
		elif DOTFILES="$(readlink ~mil/.profile)"; then
			echo "${DOTFILES%/HOME/.profile}"
		else
			echo ~mil/.local/dot
		fi
	)"
	sudo cp -RPp "$DOTFILES/." "${2-}$1/.local/dot"
	sudo sh -c 'cd "$1"; shift; "$@"' -- "${2-}$1/.local/dot" \
		env \
		PREFIX="$1/.local" \
		XDG_BIN_HOME="$1/.local/bin" \
		XDG_CACHE_HOME="$1/.cache" \
		XDG_CONFIG_HOME="$1/.config" \
		XDG_DATA_HOME="$1/.local/share" \
		HOME="$1" \
		dest="${2}" find . -not -type d -exec sh -c 'for i; do \
			i="${i#./}"; f="$(printenv "${i%%/*}")/${i#*/}" || continue; \
			mkdir -p "$dest${f%/*}"; ln -fs "$HOME/.local/dot/$i" "$dest$f"; \
		done' -- {} +
}

write_customization() {
	sudo mkdir -p "$ROOT/etc"
	sudo touch "$ROOT/etc/.default_boot_services"
	sudo mkdir -p "$ROOT/etc/runlevels/default"
	sudo ln -sf /etc/init.d/local "$ROOT/etc/runlevels/default"
	cp_dot "/root" "$ROOT"
	cp_dot "/home/mil" "$ROOT"

	sudo mkdir -p "$ROOT/etc/local.d"
	printf '%s\n' \
		'#!/bin/sh' \
		'set -eux' \
		'' \
		'exec </dev/null >>/var/log/local-provisioning.log 2>&1' \
		'cd /root/.local/dot/PREFIX/src/roles' \
		'' \
		| sudo tee "$ROOT/etc/local.d/init.start" >/dev/null
	[ $# -gt 0 ] || set -- \
		-s init \
		-s sysusers \
		-s apk_wrapped \
		-s networking \
		-s ntp \
		-e FOR_USER=mil -s home
	while getopts 's:e:c:' OPT "$@"; do
		case "$OPT" in
		s)
			[ ! -e "$ROOT/root/.local/dot/PREFIX/src/roles/$OPTARG/script" ] \
				|| OPTARG="$OPTARG/script"
			printf 'sh -x %s\n' "$OPTARG" \
				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
			;;
		e)
			printf 'export %s='\''%s'\''\n' "${OPTARG%%=*}" \
				"$(escape "${OPTARG#*=}")" \
				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
			;;
		c)
			printf '%s\n' "${OPTARG}" \
				| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
			;;
		*) die "ERROR: Unknown option: %OPT" ;;
		esac
	done
	shift $((OPTIND - 1)) && OPTIND=1

	printf '%s\n' \
		'' \
		'rm /etc/local.d/init.start' \
		| sudo tee -a "$ROOT/etc/local.d/init.start" >/dev/null
	sudo chmod +x "$ROOT/etc/local.d/init.start"

	printf "%s" "$HOSTNAME" | sudo tee "$ROOT/etc/hostname" >/dev/null

	if exists apk; then
		(
			set -- \
				alpine-base abuild doas-sudo-shim \
				iwd iwd-openrc bonding dbus dbus-openrc rsync \
				curl git git-perl gnupg make ncurses zsh ncurses-terminfo
			#Due to the SD card unmount
			! fnmatch 'rpi*' "$HARDWARE" \
				|| set -- "$@" linux-rpi raspberrypi-bootloader \
					alpine-base openssh openssl dosfstools e2fsprogs
			apk_repofetch -m "$ARCH" -b "$ALPINE_BRANCH" "$@"
			apk_repofetch -m "$ARCH" -b "$ALPINE_BRANCH" -p "$ROOT" "$@"
		)
	fi
}

write_distro_alpine() {
	if
		[ "$ARCH" = "$(uname_to_arch)" ] && [ "$(distro_id)" = alpine ] \
			&& [ "$HARDWARE" != live ]
	then
		ALPINE_VERSION="$(cat /etc/alpine-release)}"
		ALPINE_BRANCH="$(alpine_version_to_branch "$ALPINE_VERSION")"
		SOURCE=self
	else
		ALPINE_VERSION="${ALPINE_VERSION:-3.24.0}"
		ALPINE_BRANCH="$(alpine_version_to_branch "$ALPINE_VERSION")"
		SOURCE="$(
			if fnmatch "rpi*" "$HARDWARE"; then
				if [ "$(uname -s)" = Linux ]; then
					apk_dl releases "alpine-rpi-$ALPINE_VERSION-$ARCH.tar.gz"
				elif [ "$(uname -s)" = Darwin ]; then
					apk_dl releases "alpine-rpi-$ALPINE_VERSION-$ARCH.img.gz"
				fi
			else
				apk_dl releases "alpine-standard-$ALPINE_VERSION-$ARCH.iso"
			fi
		)"
	fi
	case "$SOURCE" in
	self)
		if
			{ [ "$HARDWARE" = standard ] && [ ! -d /sys/firmware/efi ]; } \
				|| fnmatch "rpi[1-4]" "$HARDWARE"
		then
			DISKLABEL="dos"
		else
			DISKLABEL="gpt"
		fi
		ROOT="$(mktemp -d)"
		trap clean EXIT
		if fnmatch "rpi*" "$HARDWARE" && mount | grep -q 'on /.modloop'; then
			DO_UMOUNT=1 copy-modloop
		fi
		create_root "$FILE" "$ROOT" "$DISKLABEL" "${SIZE-16G}"
		setup-disk "$ROOT"
		[ "$DISKLABEL" = gpt ] \
			|| fnmatch "rpi*" "$HARDWARE" \
			|| (</usr/share/syslinux/mbr.bin sudo tee "$FILE" >/dev/null)
		write_customization "$@"
		;;
	*.iso)
		! exists apk || sudo apk add -q xorriso
		ROOT="$(mktemp -d)"
		trap clean EXIT
		FILE="${FILE:-${SOURCE%.iso}.local.iso}"
		write_customization "$@"
		ROOTOVERLAY="$(mktemp)"
		tar -czf "$ROOTOVERLAY" -C "$ROOT" .
		if [ -b "$FILE" ]; then
			BACKING_FILE="$FILE"
			FILE="$(mktemp)"
		else
			sudo rm -f "$FILE"
		fi
		#if [ -b "$FILE" ]; then
		#    sudo wipefs -a "$FILE"
		#else
		#    sudo rm -f "$FILE"
		#fi
		sudo xorriso -indev "$SOURCE" -outdev "stdio:$FILE" \
			-boot_image any replay -map "$ROOTOVERLAY" /localhost.apkovl.tar.gz
		if [ -n "${BACKING_FILE-}" ]; then
			dd if="$FILE" of="$BACKING_FILE"
			rm "$FILE"
		else
			sudo chown "$(whoami)" "$FILE"
		fi
		rm "$ROOTOVERLAY"
		;;
	*.tar.gz)
		trap clean EXIT
		ROOT="$(mktemp -d)"
		write_customization "$@"
		ROOTOVERLAY="$(sudo mktemp)"
		sudo tar -czf "$ROOTOVERLAY" -C "$ROOT" .
		sudo rm -r "$ROOT"
		ROOT="$(mktemp -d)"
		DISKLABEL="$(fnmatch "rpi[1-4]" "$HARDWARE" && echo dos || echo gpt)"
		FILE="${FILE:-${SOURCE%.tar.gz}.img}"
		create_root "$FILE" "$ROOT" "$DISKLABEL" "${SIZE-16G}"
		sudo tar --numeric-owner -xzf "$SOURCE" -C "$ROOT/boot"
		sudo mv "$ROOTOVERLAY" "$ROOT/boot/localhost.apkovl.tar.gz"
		;;
	esac
}

write_distro_arch() {
	ROOT="$(mktemp -d)"
	trap clean EXIT
	create_root "$FILE" "$ROOT" \
		"$(fnmatch "usb" "$HARDWARE" || fnmatch "xps13" "$HARDWARE" && echo gpt || echo dos)" \
		"${SIZE-16G}"

	if [ "${HARDWARE%[1-5]}" = rpi ]; then
		echo "Actually downloading/writing data. This may take a while..." >&2
		sudo tar -xpf "$(get_rpi_image "$HARDWARE")" -C "$ROOT"
		[ "$HARDWARE" != rpi4 ] \
			|| sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
		if [ "$HARDWARE" = rpi5 ]; then
			download http://mirror.archlinuxarm.org/aarch64/core/$(
			)linux-rpi-6.6.28-1-aarch64.pkg.tar.xz \
				"${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/linux-rpi.pkg.tar.xz"
			sudo rm -rf "$ROOT/boot"/*
			sudo tar -xpf \
				"${XDG_CACHE_HOME:-$HOME/.cache}/$(
				)rpi_img/linux-rpi.pkg.tar.xz" \
				-C "$ROOT"
			<"$ROOT/boot/cmdline.txt" sed \
				"s|root=[^ ]*|root=$(get_dev_for "$ROOT")|" \
				| sudo tee "$ROOT/boot/cmdline.txt.new" >/dev/null \
				&& sudo mv "$ROOT/boot/cmdline.txt.new" \
					"$ROOT/boot/cmdline.txt"
			<"$ROOT/etc/fstab" sed \
				-e "s|/dev/mmcblk0p2|$(get_dev_for "$ROOT")|" \
				-e "s|/dev/mmcblk0p1|$(get_dev_for "$ROOT/boot")|" \
				| sudo tee "$ROOT/etc/fstab.new" >/dev/null \
				&& sudo mv "$ROOT/etc/fstab.new" "$ROOT/etc/fstab"
		fi
	else
		if [ "$HARDWARE" = live ]; then
			sudo pacman --needed --noconfirm -S archiso
			</usr/share/archiso/configs/releng/packages.x86_64 grep \
				-vE '^(#|grml-zsh-config)' \
				| to_argv sudo pacstrap "$ROOT"
		else
			sudo pacstrap "$ROOT" base linux linux-firmware \
				arch-install-scripts
		fi
	fi
	genfstab -U "$ROOT" | sudo tee "$ROOT/etc/fstab" >/dev/null
	if [ "$ARCH" = "$(uname -m)" ]; then
		cp_dot /root "$ROOT"
		cp_dot /home/mil "$ROOT"
		sudo arch-chroot "$ROOT" sh -euc '
			cd /root/.local/src/roles;
			export HOSTNAME='"$HOSTNAME"';
			export HARDWARE='"$HARDWARE"';
			./install_arch
			./init
			export FOR_USER=mil;
			./home
			printf "1234\\n1234\\n" | passwd
			usermod -aG video mil
		'
		if [ -f "$ROOT/boot/syslinux.cfg" ]; then
			BOOTDEV="$(get_dev_for "$ROOT/boot")"
			sudo umount "$ROOT/boot"
			sudo syslinux "$BOOTDEV"
			sudo dd if=/usr/lib/syslinux/bios/mbr.bin \
				of="${BACKING_FILE:-$FILE}" bs=512 conv=notrunc
		fi
	fi
}

write_os() {
	while getopts h:m:n:d:f:s:r OPT "$@"; do
		case "$OPT" in
		h) HARDWARE="$OPTARG" ;;
		m) ARCH="$OPTARG" ;;     #Same as uname
		n) HOSTNAME="$OPTARG" ;; #Same as uname
		d) DISTRO="$OPTARG" ;;
		f) FILE="$OPTARG" ;;
		s) SIZE="$OPTARG" ;;
		r) RUN=true ;;
		*) printf "ERROR: Unknown option: %s" "$OPT" >&2 && return 1 ;;
		esac
	done
	shift $((OPTIND - 1)) && OPTIND=1
	[ -n "${FILE:-}" ] || die "Specify a device/file with -f FILE"
	if [ -z "${HARDWARE-}" ]; then
		if [ -e /sys/firmware/devicetree/base/model ]; then
			HARDWARE="$(
				</sys/firmware/devicetree/base/model tr -d '\0' \
					| sed -E 's/Raspberry Pi ([0-9]).*/rpi\1/'
			)"
		elif fnmatch '/dev/nvme*' "$FILE"; then
			HARDWARE=standard
		else
			HARDWARE=live
		fi
	fi
	if [ -z "${ARCH-}" ]; then
		case "$HARDWARE" in
		rpi1) ARCH=armhf ;;
		rpi2) ARCH=armv7 ;;
		rpi[345]) ARCH=aarch64 ;;
		live) ARCH=x86_64 ;;
		standard) ARCH="$(uname_to_arch)" ;;
		esac
	fi
	DISTRO="${DISTRO-alpine}"
	case "$DISTRO" in
	alpine) write_distro_alpine "$@" ;;
	arch) write_distro_arch "$@" ;;
	esac
	if
		[ "${RUN-}" = true ] && [ "$ARCH" = x86_64 ] \
			&& [ "$(uname_to_arch)" = x86_64 ]
	then
		STTY_SETTINGS="$(stty -g)"
		qemu-system-x86_64 -m 5120 -nic user -boot order=d \
			-drive if=ide,media=disk,format=raw,file="${BACKING_FILE-$FILE}" \
			-enable-kvm -display none \
			-chardev stdio,id=serial0,signal=off \
			-serial chardev:serial0 -monitor none
		stty "$STTY_SETTINGS"
		tput smam
	fi
}

write_os "$@"
