#!/usr/bin/env sh
#shellcheck disable=SC2016
#write_os - write os to device/file
set -eu

exists() { command -v "$1" >/dev/null 2>&1; }
die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi && exit 1; }
device_of() { df -P "$1" | awk 'END { print $1 }'; }
fnmatch() { case "$2" in $1) return 0 ;; *) return 1 ;; esac }
to_argv() (
	set +x
	while read -r LINE; do set -- "$@" "$LINE"; done
	"$@"
)

clean() {
	sync
	(
		set -- boot ''
		while [ $# -ne 0 ]; do
			set -- "$(get_dev_for "$ROOT${1:+/$1}")" "$@"
			! [ -e "$ROOT${2:+/$2}" ] || [ -z "$1" ] \
				|| sudo umount "$1"
			shift 2
		done
	)
	losetup -nONAME -j "$FILE" | xargs -rn1 sudo losetup -d
	sudo rmdir "$ROOT"
}

download() { #1: url, 2: path
	mkdir -p "$(dirname "$2")"
	if exists curl; then
		if [ -e "$2" ]; then
			curl -fLo "$2" -z "$2" "$1"
		else
			curl -fLo "$2" "$1"
		fi
	elif exists wget; then
		wget "$1" -O "$2"
	fi
}

get_rpi_image() { #1: version
	set -- "$(echo "$ARCH" | sed 's/armv6//')"
	set -- "rpi${1:+-$1}"
	set -- "http://os.archlinuxarm.org/os/ArchLinuxARM-${1}-latest.tar.gz"
	set -- "$1" "${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/${1##*/}"
	download "$@"
	echo "$2"
}

get_dev_for() { #1: path
	mount | sed -n 's_\(/dev/[^ ]*\) on '"$1"' .*_\1_p'
}

create_root() { #1: device 2: root 3: disklabel 4?: size
	mkfs.vfat --help >/dev/null 2>&1 || die "error: install mkfs.vfat"
	mkfs.ext4 2>&1 | grep -q Usage || die "error: install mkfs.ext4"

	if [ ! -b "$1" ]; then
		sudo modprobe loop
		truncate -s "$4" "$1"
		set -- "$(sudo losetup -fP --show "$1")" "$2" "$3" "${4:-}"
		expr "$1" : /dev/ >/dev/null || die "error: loopback setup failed"
		FILE="$1"
	fi
	if exists sfdisk; then
		printf 'label: '"$3"'\n,1G,'"$(
			[ "$3" = gpt ] && echo U || echo 0c
		)"',*\n,4G,S,-\n,+,L' \
			| sudo sfdisk "$1" --wipe always --wipe-partitions always
	else
		sudo wipefs -a "$1" || :
		case "$3" in
		dos)
			exists fdisk || die "error: install sfdisk or fdisk"
			echo 'o; n;p;1;;+1G; t;c; n;p;2;;8G; t;2;82;  n;p;3;;; w;q;' \
				| tr -d \  | tr ';' '\n' \
				| sudo fdisk "$1" || true #Maybe rereading part table failed
			;;
		gpt)
			exists fdisk || die "error: install sfdisk or sgdisk"
			sudo sgdisk -zo "$1"
			sudo sgdisk -n 1:0:1G -t 1:ef00 -A 2:set:2 "$1"
			if [ "$HARDWARE" = xps13 ]; then
				sudo sgdisk -n 2:+0:16G -t 3:8200 "$1"
				sudo sgdisk -N 3 -t 3:8304 "$1"
			else
				sudo sgdisk -N 2 -t 2:8304 "$1"
			fi
			;;
		esac
	fi
	sync
	sudo blockdev --rereadpt "$1" || sudo partprobe "$1" || :
	! exists mdev || mdev -s
	(
		set -- "$1" "$2" $(
			(lsblk -lnoNAME "$1" || sfdisk -l "$1" -qoDevice) \
				| sed -E '1d;s|^(/dev/)?|/dev/|' | sort
		)
		yes | sudo mkfs.ext4 "${5:-4}" && sudo mount -t ext4 "${5:-4}" "$2"
		sudo mkdir -p "$2/boot"
		yes | sudo mkfs.vfat -F 32 $3 && sudo mount -t vfat $3 "$2/boot"
		[ -z "${5:-}" ] || { sudo mkswap -L hibernate "$4"; }
	)
	[ -d "$2" ] && [ -d "$2/boot" ] || die "error: fs setup/mount failed"
}

cp_dot() { #1: new_home 2: destdir
	sudo mkdir -p "${2-}$1/.local/dot"
	DOTFILES="$(
		if [ -e "${DOTFILES-}" ]; then
			echo "$DOTFILES"
		elif DOTFILES="$(readlink ~mil/.profile)"; then
			echo "${DOTFILES%/HOME/.profile}"
		else
			echo ~mil/.local/dot
		fi
	)"
	sudo cp -RPp "$DOTFILES/." "${2-}$1/.local/dot"
	sudo sh -c 'cd "$1"; shift; "$@"' -- "${2-}$1/.local/dot" \
		env \
		PREFIX="$1/.local" \
		XDG_BIN_HOME="$1/.local/bin" \
		XDG_CACHE_HOME="$1/.cache" \
		XDG_CONFIG_HOME="$1/.config" \
		XDG_DATA_HOME="$1/.local/share" \
		HOME="$1" \
		dest="${2}" find . -not -type d -exec sh -c 'for i; do \
			i="${i#./}"; f="$(printenv "${i%%/*}")/${i#*/}" || continue; \
			mkdir -p "$dest${f%/*}"; ln -fs "$HOME/.local/dot/$i" "$dest$f"; \
		done' -- {} +
}

write_distro_arch() {
	ROOT="$(mktemp -d)"
	trap clean EXIT
	create_root "$FILE" "$ROOT" \
		"$(fnmatch "rpi[1-4]" "$HARDWARE" && echo dos || echo gpt)" \
		"${SIZE-16G}"

	if [ "${HARDWARE%[1-5]}" = rpi ]; then
		echo "Actually downloading/writing data. This may take a while..." >&2
		sudo tar -xpf "$(get_rpi_image "$HARDWARE")" -C "$ROOT"
		[ "$HARDWARE" != rpi4 ] \
			|| sudo sed -i 's/mmcblk0/mmcblk1/g' "$ROOT/etc/fstab"
		if [ "$HARDWARE" = rpi5 ]; then
			download http://mirror.archlinuxarm.org/aarch64/core/$(
			)linux-rpi-6.6.28-1-aarch64.pkg.tar.xz \
				"${XDG_CACHE_HOME:-$HOME/.cache}/rpi_img/linux-rpi.pkg.tar.xz"
			sudo rm -rf "$ROOT/boot"/*
			sudo tar -xpf \
				"${XDG_CACHE_HOME:-$HOME/.cache}/$(
				)rpi_img/linux-rpi.pkg.tar.xz" \
				-C "$ROOT"
			<"$ROOT/boot/cmdline.txt" sed \
				"s|root=[^ ]*|root=$(get_dev_for "$ROOT")|" \
				| sudo tee "$ROOT/boot/cmdline.txt.new" >/dev/null \
				&& sudo mv "$ROOT/boot/cmdline.txt.new" \
					"$ROOT/boot/cmdline.txt"
			<"$ROOT/etc/fstab" sed \
				-e "s|/dev/mmcblk0p2|$(get_dev_for "$ROOT")|" \
				-e "s|/dev/mmcblk0p1|$(get_dev_for "$ROOT/boot")|" \
				| sudo tee "$ROOT/etc/fstab.new" >/dev/null \
				&& sudo mv "$ROOT/etc/fstab.new" "$ROOT/etc/fstab"
		fi
	else
		if [ "$HARDWARE" = usb ]; then
			sudo pacman --needed --noconfirm -S archiso
			</usr/share/archiso/configs/releng/packages.x86_64 grep \
				-vE '^(#|grml-zsh-config)' \
				| to_argv sudo pacstrap "$ROOT"
		else
			sudo pacstrap "$ROOT" base linux linux-firmware \
				arch-install-scripts
		fi
	fi
	genfstab -U "$ROOT" | sudo tee "$ROOT/etc/fstab" >/dev/null
	if [ "$ARCH" = "$(uname -m)" ]; then
		cp_dot /root "$ROOT"
		cp_dot /home/mil "$ROOT"
		sudo arch-chroot "$ROOT" sh -euc '
			cd /root/.local/src/roles;
			export CHROOT=true;
			export HOSTNAME='"$HOSTNAME"';
			export HARDWARE='"$HARDWARE"';
			./install_arch
			./init
			export FOR_USER=mil;
			./home
			printf "1234\\n1234\\n" | passwd
			usermod -aG video mil
		'
	fi
}

write_os() {
	while getopts h:m:f:s: OPT "$@"; do
		case "$OPT" in
		h) HARDWARE="$OPTARG" ;;
		m) ARCH="$OPTARG" ;; #Same as uname
		f) FILE="$OPTARG" ;;
		s) SIZE="$OPTARG" ;;
		*) printf "ERROR: Unknown option: %s" "$OPT" >&2 && return 1 ;;
		esac
	done
	shift $((OPTIND - 1)) && OPTIND=1
	[ -n "${FILE:-}" ] || die "Specify a device/file with -f FILE"
	if [ -z "${HARDWARE-}" ]; then
		if [ -e /sys/firmware/devicetree/base/model ]; then
			HARDWARE="$(
				</sys/firmware/devicetree/base/model tr -d '\0' \
					| sed -E 's/Raspberry Pi ([0-9]).*/rpi\1/'
			)"
		else
			HARDWARE=standard
		fi
	fi
	if [ -z "${ARCH-}" ]; then
		case "$HARDWARE" in
		rpi1) ARCH=armhf ;;
		rpi2) ARCH=armv7 ;;
		rpi[345]) ARCH=aarch64 ;;
		standard) ARCH=x86_64 ;;
		esac
	fi
	write_distro_arch
}

write_os "$@"
